#!/usr/bin/env python3
import os
import sys
from pathlib import Path

if sys.platform == 'win32':
    sys.stdout.reconfigure(encoding='utf-8')

BASE_PATH = r"C:\Users\JaZeR\OneDrive\Desktop\2026 → JaZeR Mainframe\2026 → JaZeR Master Flow Knowledge Hub\Rap_Dictionary_Master_Hub"

# 40 New W Words
WORDS = [
    {"name": "wad", "word": "Wad", "letter": "W", "meaning": "A lump or bundle of soft material/money", "rap_meaning": "Thick stack of cash, rubber band bankroll", "syllables": "1 (wad)", "pos": "Noun", "synonyms": "Stack, roll, bundle", "antonyms": "Change", "rhymes": "END: bad, mad, glad, pad, dad / SLANT: god / MULTI: ironclad", "bars": ["Pull out the wad, slap it on the counter", "Wad so thick it won't fold in the wallet", "Blew the whole wad in one night, no regrets"], "punchlines": ["Size of the bankroll", "Choking hazard (wad too big)", "Slapping sound of money"], "tags": "money, cash, rich, bundle"},
    {"name": "wager", "word": "Wager", "letter": "W", "meaning": "A gamble or bet", "rap_meaning": "Betting it all, high stakes, life is a gamble", "syllables": "2 (wa-ger)", "pos": "Noun/Verb", "synonyms": "Bet, gamble, risk", "antonyms": "Safety", "rhymes": "END: major, pager, danger, ranger / SLANT: nature / MULTI: teenager", "bars": ["Place your wager, spin the wheel of destiny", "I don't wager what I can't afford to lose", "Maximum wager, all in on myself"], "punchlines": ["Casino imagery", "High stakes risk", "Betting on yourself"], "tags": "gamble, risk, money, bet"},
    {"name": "wagon", "word": "Wagon", "letter": "W", "meaning": "Four-wheeled vehicle", "rap_meaning": "G-Wagon (Benz), hopping on/off the bandwagon", "syllables": "2 (wag-on)", "pos": "Noun", "synonyms": "Truck, car", "antonyms": "Sedan", "rhymes": "END: dragon, flagon, laggin / SLANT: bag / MULTI: band-wagon", "bars": ["Matte black Wagon, G-class monster", "Don't jump on the wagon now that we winning", "Off the wagon, back on the grind"], "punchlines": ["Mercedes G-Wagon", "Bandwagon fans", "Sobriety metaphor"], "tags": "car, benz, fake, ride"},
    {"name": "wake", "word": "Wake", "letter": "W", "meaning": "To stop sleeping; trail of water; funeral watch", "rap_meaning": "Stay woke, leave enemies in the wake, funeral service", "syllables": "1 (wake)", "pos": "Verb/Noun", "synonyms": "Rise, trail, funeral", "antonyms": "Sleep", "rhymes": "END: bake, cake, lake, snake, shake / SLANT: back / MULTI: earthquake", "bars": ["Wake up and smell the coffee/money", "Leave 'em in my wake, drowning in the waves", "Attend your own wake if you try me"], "punchlines": ["Stay Woke political/social", "Boat speed imagery", "Death threat"], "tags": "conscious, speed, death, rise"},
    {"name": "wall", "word": "Wall", "letter": "W", "meaning": "Continuous vertical brick structure", "rap_meaning": "Hitting the wall, back against the wall, Wall Street, barrier", "syllables": "1 (wall)", "pos": "Noun", "synonyms": "Barrier, fence", "antonyms": "Door", "rhymes": "END: ball, call, fall, tall, mall / SLANT: well / MULTI: alcohol", "bars": ["Back against the wall is when I fight hardest", "Build a wall around the heart, no entry", "Talking to the wall cause you don't listen"], "punchlines": ["No escape scenario", "Trump/Border wall metaphors", "Wall Street money"], "tags": "barrier, trap, money, defense"},
    {"name": "wallet", "word": "Wallet", "letter": "W", "meaning": "Pocket-sized flat folding case for money", "rap_meaning": "Bank account, spending power, crypto wallet", "syllables": "2 (wal-let)", "pos": "Noun", "synonyms": "Billfold, purse", "antonyms": "Pocket", "rhymes": "END: mallet, pallet, valet / SLANT: solid / MULTI: ballot", "bars": ["Wallet looking healthy, gained some weight", "Crypto wallet password lost, painful memory", "Hit the wallet not the face, hurt 'em financially"], "punchlines": ["Fat wallet vs Skinny wallet", "Lost keys/crypto", "Spending power"], "tags": "money, cash, wealth, crypto"},
    {"name": "wander", "word": "Wander", "letter": "W", "meaning": "Walk or move in a leisurely or aimless way", "rap_meaning": "Lost in thought, eyes wandering (cheating), exploring the world", "syllables": "2 (wan-der)", "pos": "Verb", "synonyms": "Roam, stray", "antonyms": "Stay", "rhymes": "END: ponder, yonder, squander / SLANT: wonder / MULTI: beyond her", "bars": ["Mind wander to the money during the convo", "Don't let your eyes wander to my plate", "Wander the globe, nomadic lifestyle"], "punchlines": ["Focus issues", "Jealousy/Envy", "Travel flex"], "tags": "travel, lost, focus, roam"},
    {"name": "warden", "word": "Warden", "letter": "W", "meaning": "Person responsible for supervision (prison)", "rap_meaning": "The boss, prison control, gatekeeper", "syllables": "2 (war-den)", "pos": "Noun", "synonyms": "Guard, boss", "antonyms": "Inmate", "rhymes": "END: garden, pardon, harden / SLANT: margin / MULTI: jordan", "bars": ["Warden of the block, I control the keys", "Ask the warden for a pardon, deny the request", "Gatekeeper trying to play warden with the culture"], "punchlines": ["Prison hierarchy", "Rick Ross reference (Officer/Warden)", "Control freak"], "tags": "prison, control, police, boss"},
    {"name": "wardrobe", "word": "Wardrobe", "letter": "W", "meaning": "Large cabinet for clothes", "rap_meaning": "Closet full of designer, Narnia (magic), changing styles", "syllables": "2 (ward-robe)", "pos": "Noun", "synonyms": "Closet, clothes", "antonyms": "Naked", "rhymes": "END: probe, globe, lobe, robe / SLANT: job / MULTI: earlobe", "bars": ["Wardrobe malfunction, too much ice exposed", "Step into the wardrobe, come out a king", "Designer wardrobe, value of a house"], "punchlines": ["Narnia reference", "Fashion flex", "Cost of clothes"], "tags": "fashion, clothes, expensive, style"},
    {"name": "warfare", "word": "Warfare", "letter": "W", "meaning": "Engagement in war", "rap_meaning": "Psychological warfare, street battles, advanced tactics", "syllables": "2 (war-fare)", "pos": "Noun", "synonyms": "Combat, battle", "antonyms": "Peace", "rhymes": "END: welfare, healthcare, nightmare / SLANT: air / MULTI: software", "bars": ["Mental warfare, I break you before I touch you", "Guerrilla warfare in the concrete jungle", "Modern warfare, drones and phones"], "punchlines": ["Call of Duty reference", "Sun Tzu tactics", "Street strategies"], "tags": "war, fight, strategy, street"},
    {"name": "warning", "word": "Warning", "letter": "W", "meaning": "Statement of danger", "rap_meaning": "Warning shots, threats, parental advisory", "syllables": "2 (warn-ing)", "pos": "Noun", "synonyms": "Threat, alert", "antonyms": "Welcome", "rhymes": "END: morning, mourning, yawning / SLANT: burning / MULTI: swarming", "bars": ["Warning shots in the air, next one hits", "Heeded the warning but it was too late", "Parental Advisory Warning on the cover"], "punchlines": ["Gunshots", "Music industry label", "Omen"], "tags": "danger, threat, gun, label"},
    {"name": "warrant", "word": "Warrant", "letter": "W", "meaning": "Legal paper authorizing an arrest/search", "rap_meaning": "Police searching, having a warrant out, justifying actions", "syllables": "2 (war-rant)", "pos": "Noun", "synonyms": "Order, license", "antonyms": "Ban", "rhymes": "END: torrent, current, abhorrent / SLANT: parent / MULTI: deterrent", "bars": ["Feds got a warrant, flush the work", "Active warrant so I move in the shadows", "My skills warrant the high price tag"], "punchlines": ["Police raid imagery", "Legal trouble", "Justification of worth"], "tags": "police, law, legal, trouble"},
    {"name": "warrior", "word": "Warrior", "letter": "W", "meaning": "Brave or experienced soldier", "rap_meaning": "Fighter, survivor, Golden State Warriors (winning)", "syllables": "3 (war-rior)", "pos": "Noun", "synonyms": "Soldier, fighter", "antonyms": "Coward", "rhymes": "END: courier, worrier / SLANT: lawyer / MULTI: terrier", "bars": ["Heart of a warrior, spirit of a king", "Weekend warrior vs career soldier", "Shooting like a Warrior, call me Steph"], "punchlines": ["Steph Curry/NBA reference", "Medieval battle", "Survivor spirit"], "tags": "fight, brave, soldier, nba"},
    {"name": "wash", "word": "Wash", "letter": "W", "meaning": "Clean with water; money laundering", "rap_meaning": "Washing money, washed up (old), cleaning the scene", "syllables": "1 (wash)", "pos": "Verb", "synonyms": "Clean, scrub", "antonyms": "Dirty", "rhymes": "END: mosh, posh, squash, nosh / SLANT: cash / MULTI: macintosh", "bars": ["Wash the money till it's clean and legal", "You washed up, retirement home calling", "It all comes out in the wash, truth reveals"], "punchlines": ["Laundromat/Money laundering", "Career end insult", "Hygiene"], "tags": "clean, money, old, crime"},
    {"name": "waste", "word": "Waste", "letter": "W", "meaning": "Use carelessly; trash; kill", "rap_meaning": "Wasting time, wasted (drunk), wasting enemies (kill), waist (gun)", "syllables": "1 (waste)", "pos": "Verb/Noun", "synonyms": "Squander, trash", "antonyms": "Save", "rhymes": "END: taste, haste, paste, chaste, based / SLANT: face / MULTI: erased", "bars": ["Don't waste my time, time is currency", "Get wasted at the party, wake up regretful", "Waste the competition, leave no trace"], "punchlines": ["GTA 'Wasted' screen", "Time management", "Violence"], "tags": "time, drug, kill, trash"},
    {"name": "watch", "word": "Watch", "letter": "W", "meaning": "Look at; timepiece", "rap_meaning": "Rolex/Patek/AP, watching the block, surveillance", "syllables": "1 (watch)", "pos": "Noun/Verb", "synonyms": "Look, time", "antonyms": "Ignore", "rhymes": "END: scotch, notch, botch, crotch / SLANT: touch / MULTI: hopscotch", "bars": ["Watch cost a house, time is money literally", "Watch who you trust, snakes in the garden", "Watch the throne, I'm coming for the seat"], "punchlines": ["Jewelry flex (AP/Rolex)", "Paranoia/Surveillance", "Jay-Z/Kanye reference"], "tags": "jewelry, time, money, see"},
    {"name": "water", "word": "Water", "letter": "W", "meaning": "H2O; clear liquid", "rap_meaning": "Diamonds (water/ice), flow (Bruce Lee), whipping work", "syllables": "2 (wa-ter)", "pos": "Noun", "synonyms": "Liquid, aqua", "antonyms": "Fire", "rhymes": "END: daughter, slaughter, quarter / SLANT: order / MULTI: mortar", "bars": ["Neck covered in water, call the plumber", "Be water my friend, formless and shapeless", "Trap water, whipping till the wrist lock"], "punchlines": ["Jewelry clarity (VVS)", "Bruce Lee philosophy", "Cooking crack"], "tags": "jewelry, flow, element, cook"},
    {"name": "wave", "word": "Wave", "letter": "W", "meaning": "Ridge of water; gesture; trend", "rap_meaning": "The trend/style, creating a wave, hair waves, waving goodbye", "syllables": "1 (wave)", "pos": "Noun", "synonyms": "Trend, tide", "antonyms": "Still", "rhymes": "END: save, brave, cave, pave, grave / SLANT: have / MULTI: behave", "bars": ["Ride the wave or drown in the current", "I started this wave, you just surfing", "360 waves spinning, seasick on land"], "punchlines": ["Surfing metaphor", "Hair style (durag)", "Trendsetter vs Follower"], "tags": "trend, style, water, hair"},
    {"name": "wax", "word": "Wax", "letter": "W", "meaning": "Beeswax; vinyl record; to increase", "rap_meaning": "On wax (recorded), wax museum (fake people), waxing cars (Karate Kid)", "syllables": "1 (wax)", "pos": "Noun/Verb", "synonyms": "Record, polish", "antonyms": "Wane", "rhymes": "END: tax, ax, max, facts, relax / SLANT: sex / MULTI: climax", "bars": ["Put it on wax, now it's forever history", "Stop waxing poetic and show me the facts", "Wax on, wax off, training for the title"], "punchlines": ["Vinyl/Music recording", "Miyagi training", "Candle melting"], "tags": "music, record, shine, fight"},
    {"name": "weak", "word": "Weak", "letter": "W", "meaning": "Lacking strength", "rap_meaning": "Soft, fake, lame bars, weak sauce", "syllables": "1 (weak)", "pos": "Adjective", "synonyms": "Fraile, soft", "antonyms": "Strong", "rhymes": "END: peak, speak, cheek, geek, seek / SLANT: break / MULTI: technique", "bars": ["Your whole crew weak, structure crumbling", "Weak link in the chain gets cut loose", "Spirit is willing but the bars are weak"], "punchlines": ["Chain link metaphor", "Workout/Gym roast", "Bible quote flip"], "tags": "insult, soft, flawed, lame"},
    {"name": "weapon", "word": "Weapon", "letter": "W", "meaning": "Thing used to inflict harm", "rap_meaning": "Gun, the mind/lyrics as a weapon, lethal skills", "syllables": "2 (weap-on)", "pos": "Noun", "synonyms": "Arm, tool, gun", "antonyms": "Shield", "rhymes": "END: step in, prepin, zeppelin / SLANT: happen / MULTI: threaten", "bars": ["Concealed weapon is the intellect", "My flow a lethal weapon, Danny Glover style", "Formed against me but the weapon won't prosper"], "punchlines": ["Lethal Weapon movie", "Bible quote (Isiah 54:17)", "Hidden talent"], "tags": "gun, fight, dangerous, tool"},
    {"name": "weave", "word": "Weave", "letter": "W", "meaning": "Form fabric; hair extension; move side to side", "rap_meaning": "Driving (weaving traffic), hair weave, storytelling (weaving tales)", "syllables": "1 (weave)", "pos": "Verb/Noun", "synonyms": "Knit, dodge", "antonyms": "Straight", "rhymes": "END: leave, sleeve, believe, eve, grieve / SLANT: give / MULTI: deceive", "bars": ["Weave through the traffic, GT3 dashing", "Pulling out the weave, fight in the club", "Weave a web of lies, get caught in the net"], "punchlines": ["Driving skill", "Hair extension insult", "Spider web"], "tags": "drive, hair, story, move"},
    {"name": "web", "word": "Web", "letter": "W", "meaning": "Spider's network; internet", "rap_meaning": "World wide web, trap (spider web), complex network/lies", "syllables": "1 (web)", "pos": "Noun", "synonyms": "Net, trap", "antonyms": "Freedom", "rhymes": "END: ebb, deb, celeb / SLANT: lab / MULTI: cobweb", "bars": ["Caught in the web of the system, can't move", "Worldwide web connection, download the money", "Spider-Man web, swinging through the city"], "punchlines": ["Spiderman", "Internet/Dark Web", "Trap/Lies"], "tags": "trap, internet, network, lies"},
    {"name": "weight", "word": "Weight", "letter": "W", "meaning": "Heaviness; importance; drugs", "rap_meaning": "Moving weight (selling bricks), carrying the weight of the team, pressure", "syllables": "1 (weight)", "pos": "Noun", "synonyms": "Heavy, load", "antonyms": "Light", "rhymes": "END: fate, gate, hate, rate, state / SLANT: height / MULTI: debate", "bars": ["Moving heavy weight, forklift needed", "Weight of the world, bench press the planet", "Wait/Weight is over, I'm delivering now"], "punchlines": ["Drug dealing scale", "Gym/Lifting", "Homophone (Wait/Weight)"], "tags": "drugs, heavy, pressure, gym"},
    {"name": "welcome", "word": "Welcome", "letter": "W", "meaning": "Greeting", "rap_meaning": "Welcome to the jungle, welcome mats, invitation", "syllables": "2 (wel-come)", "pos": "Noun/Verb", "synonyms": "Hello, entry", "antonyms": "Goodbye", "rhymes": "END: seldon, well done / SLANT: home / MULTI: outcome", "bars": ["Welcome to the party, leave your phone at the door", "Overstayed your welcome, time to exit", "Welcome mat is actually a trap door"], "punchlines": ["Guns N Roses (Jungle)", "Hospitality trap", "Kick out"], "tags": "greet, enter, start, polite"},
    {"name": "west", "word": "West", "letter": "W", "meaning": "Direction", "rap_meaning": "West Coast (Best Coast), Westside signs, Kanye (West)", "syllables": "1 (west)", "pos": "Noun", "synonyms": "Left, sunset", "antonyms": "East", "rhymes": "END: best, chest, test, rest, blessed / SLANT: wrist / MULTI: request", "bars": ["Westside connection, throw the W up", "Heading West like pioneers for the gold", "Kanye West confidence, I am a god"], "punchlines": ["Hand signs (W)", "Tupac/West Coast", "Kanye reference"], "tags": "direction, gang, place, kanye"},
    {"name": "wet", "word": "Wet", "letter": "W", "meaning": "Covered in liquid", "rap_meaning": "PCP (Sherm/Wet), getting someone wet (shooting), jewelry shine", "syllables": "1 (wet)", "pos": "Adjective", "synonyms": "Soaked, damp", "antonyms": "Dry", "rhymes": "END: bet, get, jet, net, set / SLANT: fit / MULTI: sunset", "bars": ["Necklace leave the shirt wet, dripping hard", "Smoking on that wet, mind gone", "Leave the scene wet, stormy weather"], "punchlines": ["Jewelry drip", "Drug slang", "Violence"], "tags": "water, drugs, jewelry, violence"},
    {"name": "whale", "word": "Whale", "letter": "W", "meaning": "Large marine mammal", "rap_meaning": "Big spender in casino (Whale), fat pockets, huge", "syllables": "1 (whale)", "pos": "Noun", "synonyms": "Giant, leviathan", "antonyms": "Minnow", "rhymes": "END: fail, jail, mail, sale, tail / SLANT: well / MULTI: detail", "bars": ["Casino boss calling me a whale, big chips", "Ahab searching for the whale, I'm Moby Dick", "Belly of the whale, swallowed by the struggle"], "punchlines": ["Casino terminology", "Moby Dick comparison", "Jonah bible story"], "tags": "money, big, animal, gamble"},
    {"name": "whip", "word": "Whip", "letter": "W", "meaning": "To beat; a car; steering wheel", "rap_meaning": "Nice car, whipping the pot (cooking crack), punishment", "syllables": "1 (whip)", "pos": "Noun/Verb",
    "synonyms": "Car, beat, stir", "antonyms": "Walk", "rhymes": "END: dip, grip, lip, rip, ship / SLANT: step / MULTI: trip", "bars": ["New whip, push button start, ghost ride", "Whip inside the kitchen, wrist game strong", "Crack the whip, make the workers move"], "punchlines": ["Car flex", "Cooking drugs", "Slavery/Master imagery"], "tags": "car, cook, drugs, drive"},
    {"name": "whisper", "word": "Whisper", "letter": "W", "meaning": "Speak softly", "rap_meaning": "Secret talk, silenced gun, rumors", "syllables": "2 (whis-per)", "pos": "Verb/Noun", "synonyms": "Mutter, hush", "antonyms": "Yell", "rhymes": "END: crisper, lister / SLANT: sister / MULTI: blister", "bars": ["Whisper song style, Ying Yang Twins flow", "Gun got a whisper, silencer fitted", "Careless whispers start wars in the streets"], "punchlines": ["Wait till you see my... (Ying Yang Twins)", "Silencer sound", "Rumor mill"], "tags": "quiet, secret, gun, talk"},
    {"name": "white", "word": "White", "letter": "W", "meaning": "Color", "rap_meaning": "Cocaine (White girl), Off-White brand, white collar crime, innocence", "syllables": "1 (white)", "pos": "Noun/Adjective", "synonyms": "Pale, snow", "antonyms": "Black", "rhymes": "END: light, bright, fight, night, sight / SLANT: wet / MULTI: dynamite", "bars": ["Selling that white, Barry White voice deep", "Off-White on the kicks, Virgil legacy", "White collar crime pays better than the block"], "punchlines": ["Drug slang", "Fashion (Off-White)", "Race/Society commentary"], "tags": "color, drug, fashion, crime"},
    {"name": "wicked", "word": "Wicked", "letter": "W", "meaning": "Evil or morally wrong; awesome (slang)", "rap_meaning": "Evil intentions, John Wick style, Boston slang", "syllables": "2 (wick-ed)", "pos": "Adjective", "synonyms": "Evil, bad", "antonyms": "Good", "rhymes": "END: ticket, cricket, picket / SLANT: kick it / MULTI: explicit", "bars": ["Something wicked this way comes, storm brewing", "Wicked jump shot, Boston Garden range", "No rest for the wicked, money don't sleep"], "punchlines": ["Bible quote", "John Wick violence", "Boston slang"], "tags": "evil, bad, cool, fight"},
    {"name": "wide", "word": "Wide", "letter": "W", "meaning": "Broad width", "rap_meaning": "Worldwide, wide body kit (cars), wide receiver", "syllables": "1 (wide)", "pos": "Adjective",
    "synonyms": "Broad, large", "antonyms": "Narrow", "rhymes": "END: hide, ride, side, slide, tide / SLANT: wood / MULTI: divide", "bars": ["Wide body Porsche, taking up two lanes", "Open wide, swallow the truth", "World wide web, trapped in the net"], "punchlines": ["Car modification", "Football (Wide Receiver)", "Scope of influence"], "tags": "big, car, range, size"},
    {"name": "wild", "word": "Wild", "letter": "W", "meaning": "Untamed", "rap_meaning": "Wild 'n Out, crazy party, wild west, dangerous", "syllables": "1 (wild)", "pos": "Adjective",
    "synonyms": "Crazy, savage", "antonyms": "Tame", "rhymes": "END: child, mild, filed, piled / SLANT: world / MULTI: exiled", "bars": ["Wild for the night, A$AP Rocky vibes", "Wild West mentality, shooters on horses", "Running wild, lost child in the city"], "punchlines": ["Nick Cannon usage", "Western movie", "Party mode"], "tags": "crazy, party, dangerous, fun"},
    {"name": "win-win", "word": "Win-win", "letter": "W", "meaning": "Beneficial to both", "rap_meaning": "Good business deal, I win you win, positive outcome", "syllables": "2 (win-win)", "pos": "Noun",
    "synonyms": "Mutal, deal", "antonyms": "Zero-sum", "rhymes": "END: skin, chin, bin / SLANT: when / MULTI: violin", "bars": ["It's a win-win, we both eat at the table", "Looking for the win-win but prepared for the take-all", "No win-win here, I need the whole pie"], "punchlines": ["Business negotiation", "Optimism vs Realism", "Tie game"], "tags": "business, success, deal, positive"},
    {"name": "wind", "word": "Wind", "letter": "W", "meaning": "Moving air; to turn/twist", "rap_meaning": "Gone with the wind, second wind (energy), winding roads, Chicago (Windy City)", "syllables": "1 (wind)", "pos": "Noun/Verb", "synonyms": "Air, breeze", "antonyms": "Still", "rhymes": "END: mind, grind, find, blind, kind / SLANT: end / MULTI: behind", "bars": ["Caught my second wind, extra innings hustle", "Windy City blowing, cold hearted streets", "Gone with the wind, haters disappeared"], "punchlines": ["Chicago reference", "Stamina metaphor", "Disappearing act"], "tags": "city, air, fast, energy"},
    {"name": "window", "word": "Window", "letter": "W", "meaning": "Opening in wall", "rap_meaning": "Window of opportunity, window shopper (broke), tint", "syllables": "2 (win-dow)", "pos": "Noun", "synonyms": "Pane, opening", "antonyms": "Wall", "rhymes": "END: indo, crescendo / SLANT: into / MULTI: nintendo", "bars": ["Window of opportunity closing, jump through", "Window shopper flow, you just looking not buying", "Tinted window, can't see who driving the ghost"], "punchlines": ["50 Cent reference (Window Shopper)", "Time limit metaphor", "Car flex"], "tags": "opportunity, car, look, broke"},
    {"name": "wine", "word": "Wine", "letter": "W", "meaning": "Alcoholic grape drink", "rap_meaning": "Aging like fine wine, expensive taste, spilling wine (blood)", "syllables": "1 (wine)", "pos": "Noun", "synonyms": "Vino, drink", "antonyms": "Water", "rhymes": "END: dine, fine, line, mine, shine / SLANT: win / MULTI: design", "bars": ["Aged like fine wine, getting better with time", "Sipping wine in Italy, mob ties", "Red wine on the carpet, murder scene decor"], "punchlines": ["Aging well", "Luxury/Class", "Blood metaphor"], "tags": "drink, class, old, blood"},
    {"name": "wing", "word": "Wing", "letter": "W", "meaning": "Part of bird/plane; extension", "rap_meaning": "Wingman, taking flight, winging it (freestyle), chicken wings (Rick Ross)", "syllables": "1 (wing)", "pos": "Noun", "synonyms": "Flap, limb", "antonyms": "Root", "rhymes": "END: king, ring, sing, bring, thing / SLANT: wrong / MULTI: earring", "bars": ["Take you under my wing, teach you the game", "Lemon pepper wings, Rick Ross lifestyle", "On a wing and a prayer, flying blind"], "punchlines": ["Rick Ross/Lemon Pepper", "Mentorship", "Flight"], "tags": "fly, food, teach, help"},
    {"name": "wire", "word": "Wire", "letter": "W", "meaning": "Metal thread; money transfer; recording device", "rap_meaning": "The Wire (HBO), wearing a wire (snitch), wiring money", "syllables": "1 (wire)", "pos": "Noun/Verb", "synonyms": "Cable, line", "antonyms": "Wireless", "rhymes": "END: fire, hire, liar, tire, empire / SLANT: air / MULTI: desire", "bars": ["Wire transfer hit the account, international", "Wearing a wire, talking to the Feds", "Down to the wire, clutch performance"], "punchlines": ["HBO Show reference", "Snitch detection", "Money transfer"], "tags": "money, police, snitch, tv"},
    {"name": "wish", "word": "Wish", "letter": "W", "meaning": "Desire for something", "rap_meaning": "Wishful thinking, Make-A-Wish, wishing on a star", "syllables": "1 (wish)", "pos": "Verb/Noun", "synonyms": "Hope, dream", "antonyms": "Reality", "rhymes": "END: fish, dish, swish / SLANT: wash / MULTI: english", "bars": ["Wish a haters would, try me", "Make a wish, blow the candles out on your career", "Ordered you off Wish, cheap knockoff version"], "punchlines": ["Wish.com (cheap/fake)", "Threat (wish a...)", "Basketball (swish/wish)"], "tags": "dream, fake, hope, want"},
]

def create_word(word_data):
    letter = word_data["letter"]
    letter_path = Path(BASE_PATH) / letter
    words_base_path = letter_path / "01_Words"
    words_base_path.mkdir(parents=True, exist_ok=True)
    word_folder = words_base_path / word_data["name"]
    word_folder.mkdir(exist_ok=True)

    template = f"""# WORD: {word_data["word"]}

## Meaning (plain):
{word_data["meaning"]}

## Rap meaning (how I'd say it):
{word_data["rap_meaning"]}

## Syllables:
{word_data["syllables"]}

## Part of speech:
{word_data["pos"]}

## Synonyms:
{word_data["synonyms"]}

## Antonyms:
{word_data["antonyms"]}

## Rhyme ideas (end / slant / multi):
{word_data["rhymes"]}

## 3 bar-ready examples:
1. {word_data["bars"][0]}
2. {word_data["bars"][1]}
3. {word_data["bars"][2]}

## 3 punchline angles:
1. {word_data["punchlines"][0]}
2. {word_data["punchlines"][1]}
3. {word_data["punchlines"][2]}

## Tags:
{word_data["tags"]}
"""
    word_file = word_folder / "word.md"
    word_file.write_text(template, encoding='utf-8')
    print(f"[+] Created: {letter}/{word_data['name']}")

def main():
    print(f"Adding 40 remaining W words...")
    for word_data in WORDS:
        create_word(word_data)
    print(f"Done with W.")

if __name__ == "__main__":
    main()
