#!/usr/bin/env python3
import os
import sys
from pathlib import Path

if sys.platform == 'win32':
    sys.stdout.reconfigure(encoding='utf-8')

BASE_PATH = r"C:\Users\JaZeR\OneDrive\Desktop\2026 → JaZeR Mainframe\2026 → JaZeR Master Flow Knowledge Hub\Rap_Dictionary_Master_Hub"

# 40 New V Words
WORDS = [
    {"name": "vacancy", "word": "Vacancy", "letter": "V", "meaning": "Unoccupied position or place", "rap_meaning": "Spot at the top open, nobody home (dumb), dead eyes", "syllables": "3 (va-can-cy)", "pos": "Noun", "synonyms": "Opening, void", "antonyms": "Full", "rhymes": "END: agency, pregnancy, flagrancy / SLANT: see / MULTI: complacency", "bars": ["No vacancy in my circle, we full", "Vacancy in your eyes, lights on nobody home", "There's a vacancy for the King spot, I'm moving into"], "punchlines": ["Hotel motel imagery", "Head empty insult", "Position taking"], "tags": "empty, spot, circle, dumb"},
    {"name": "vacation", "word": "Vacation", "letter": "V", "meaning": "Holidy, time off", "rap_meaning": "Permanent vacation (death/prison), taking a break, global travel", "syllables": "3 (va-ca-tion)", "pos": "Noun", "synonyms": "Trip, break", "antonyms": "Work", "rhymes": "END: nation, station, creation, sensation / SLANT: patience / MULTI: inflation", "bars": ["Put them on permanent vacation, dirt nap", "I don't need a vacation, I love the grind", "My life is a vacation, you just visiting"], "punchlines": ["Death euphemism", "Grindset no days off", "Luxury lifestyle"], "tags": "trip, break, death, fun"},
    {"name": "vaccine", "word": "Vaccine", "letter": "V", "meaning": "Immunity shot", "rap_meaning": "Cure for the fake, injected with truth, immunity to haters", "syllables": "2 (vac-cine)", "pos": "Noun", "synonyms": "Shot, cure", "antonyms": "Virus", "rhymes": "END: seen, marine, green, queen / SLANT: scene / MULTI: quarantine", "bars": ["I'm the vaccine for the mumble rap virus", "Immune to the hate, took the vaccine early", "Injecting the game with the vaccine of realness"], "punchlines": ["Medical metaphor", "Sickness vs Cure", "Pandemic reference"], "tags": "health, cure, real, sick"},
    {"name": "vacuum", "word": "Vacuum", "letter": "V", "meaning": "Space devoid of matter; cleaner", "rap_meaning": "Power vacuum (leader gone), sucking up clout, cleaning the streets", "syllables": "2 (vac-uum)", "pos": "Noun", "synonyms": "Void, cleaner", "antonyms": "Matter", "rhymes": "END: costume, resume, perfume / SLANT: room / MULTI: volume", "bars": ["Fill the power vacuum when the boss falls", "Vacuum seal the pack, freshness guaranteed", "Suckers exist in a vacuum, I breathe air"], "punchlines": ["Power struggle", "Drug packaging", "Nature abhors a vacuum"], "tags": "empty, clean, drugs, power"},
    {"name": "vagabond", "word": "Vagabond", "letter": "V", "meaning": "Wanderer without a home", "rap_meaning": "Hustler on the move, no address, street walker, nomad", "syllables": "3 (vag-a-bond)", "pos": "Noun", "synonyms": "Nomad, drifter", "antonyms": "Resident", "rhymes": "END: bond, pond, fond, wand / SLANT: beyond / MULTI: respond", "bars": ["Vagabond lifestyle, suitcase is my home", "Rich vagabond, touring the globe", "Don't treat me like a vagabond, I own the block"], "punchlines": ["Travel flex", "Homeless vs Global", "Nomad spirit"], "tags": "travel, homeless, move, street"},
    {"name": "vague", "word": "Vague", "letter": "V", "meaning": "Uncertain, indefinite", "rap_meaning": "Not clear, hiding something, shady behavior, subliminal disses", "syllables": "1 (vague)", "pos": "Adjective", "synonyms": "Unclear, hazy", "antonyms": "Clear", "rhymes": "END: plague, league / SLANT: big / MULTI: intrigue", "bars": ["Keep it vague with the cops, never specific", "Vague threats don't move me, say my name", "Future vague for you, crystal clear for me"], "punchlines": ["Interrogation tactics", "Subliminal diss", "Vision clarity"], "tags": "secret, shade, unclear, police"},
    {"name": "vain", "word": "Vain", "letter": "V", "meaning": "High opinion of appearance; useless", "rap_meaning": "Thinking you're the song, vain attempts to stop me, vanity", "syllables": "1 (vain)", "pos": "Adjective", "synonyms": "Proud, futile", "antonyms": "Humble", "rhymes": "END: rain, pain, chain, brain, train / SLANT: vein / MULTI: insane", "bars": ["You so vain, probably think this bar is about you", "Struggle in vain, you can't stop the inevitable", "Vain glory, chasing likes instead of respect"], "punchlines": ["Carly Simon reference", "Futile effort", "Narcissism"], "tags": "ego, useless, proud, look"},
    {"name": "valentine", "word": "Valentine", "letter": "V", "meaning": "Lover; February 14", "rap_meaning": "My gun (funny valentine), sweet heart, massacre (St. Valentines)", "syllables": "3 (val-en-tine)", "pos": "Noun", "synonyms": "Love, date", "antonyms": "Enemy", "rhymes": "END: wine, mine, shine, line, nine / SLANT: time / MULTI: turpentine", "bars": ["My funny valentine happens to carry nine bullets", "St. Valentine's Day Massacre style execution", "Be my valentine, or be my victim"], "punchlines": ["Gun as girlfriend", "History (Massacre)", "Romance twist"], "tags": "love, gun, kill, date"},
    {"name": "valid", "word": "Valid", "letter": "V", "meaning": "Logically sound; accepted", "rap_meaning": "Certified in the streets, official, check clears, legit", "syllables": "2 (val-id)", "pos": "Adjective", "synonyms": "Real, legit", "antonyms": "Fake", "rhymes": "END: salad, ballad, pallid / SLANT: solid / MULTI: invalid", "bars": ["Card valid, swipe goes through every time", "You not valid in your own hood, pass revoked", "Argument valid, but I still don't care"], "punchlines": ["Credit card check", "Street cred verification", "Certification"], "tags": "real, money, street, pass"},
    {"name": "valley", "word": "Valley", "letter": "V", "meaning": "Low area between hills", "rap_meaning": "Low points in life, Valley of Death, Silicon Valley (tech money)", "syllables": "2 (val-ley)", "pos": "Noun", "synonyms": "Dale, low", "antonyms": "Hill", "rhymes": "END: alley, rally, tally, sally / SLANT: belly / MULTI: finale", "bars": ["Walk through the valley of the shadow of death", "Peaks and valleys, I survived the lows", "Silicon Valley money, tech startup flow"], "punchlines": ["Bible quote (Psalm 23)", "Life ups and downs", "California location"], "tags": "low, death, money, place"},
    {"name": "value", "word": "Value", "letter": "V", "meaning": "Worth; principles", "rap_meaning": "Net value, knowing your value, adding value to the team", "syllables": "2 (val-ue)", "pos": "Noun", "synonyms": "Worth, price", "antonyms": "Cost", "rhymes": "END: menu, venue / SLANT: you / MULTI: avenue", "bars": ["Add tax to my value, price going up", "You bring no value to the table, just an appetite", "Depreciating value like a new car, you falling off"], "punchlines": ["Self-worth vs Net worth", "Business asset", "Economics"], "tags": "money, worth, business, self"},
    {"name": "vampire", "word": "Vampire", "letter": "V", "meaning": "Blood sucker", "rap_meaning": "Sucking the life out of the game, up all night, staying young forever, Playboi Carti vibe", "syllables": "2 (vam-pire)", "pos": "Noun", "synonyms": "Dracula, leech", "antonyms": "Human", "rhymes": "END: empire, fire, wire, tire / SLANT: here / MULTI: umpire", "bars": ["Vampire life, sleep all day party all night", "Energy vampires trying to suck my glow", "Built an empire moving like a vampire in shadows"], "punchlines": ["No reflection in mirror", "Sucking blood/energy", "Carti/Punk aesthetic"], "tags": "monster, night, blood, fake"},
    {"name": "van", "word": "Van", "letter": "V", "meaning": "Vehicle", "rap_meaning": "Jump out boys (police van), tour van, kidnapping (throw in the van)", "syllables": "1 (van)", "pos": "Noun", "synonyms": "Truck, bus", "antonyms": "Car", "rhymes": "END: can, man, fan, plan, scan / SLANT: then / MULTI: sedan", "bars": ["Black van pull up, everybody scatter", "Started in a tour van, now it's private jets", "Throw the bag in the van, secure the package"], "punchlines": ["Kidnapping imagery", "Police raid", "Humble beginnings"], "tags": "car, police, tour, trap"},
    {"name": "vandal", "word": "Vandal", "letter": "V", "meaning": "Person who destroys property", "rap_meaning": "Graffiti artist, destroying the beat, breaking rules", "syllables": "2 (van-dal)", "pos": "Noun", "synonyms": "Destroyer, thug", "antonyms": "Builder", "rhymes": "END: candle, handle, sandal / SLANT: scandal / MULTI: dismantle", "bars": ["Vandalize the track, leave my tag on it", "Young vandal painting history on the walls", "Official vandal, I break what I can't fix"], "punchlines": ["Graffiti culture", "Destruction of property", "Leaving a mark"], "tags": "art, crime, break, graffiti"},
    {"name": "vanilla", "word": "Vanilla", "letter": "V", "meaning": "Flavor; plain/boring", "rap_meaning": "Soft, boring, standard, Vanilla Ice (fake), white", "syllables": "3 (va-nil-la)", "pos": "Adjective", "synonyms": "Plain, basic", "antonyms": "Chocolate", "rhymes": "END: gorilla, villa, killer, miller / SLANT: color / MULTI: chinchilla", "bars": ["Your style vanilla, no flavor just basic", "Vanilla Sky, dreaming with eyes open", "I go gorilla, you go vanilla, different species"], "punchlines": ["Ice cream flavor text", "Vanilla Ice reference", "Boring vs Exciting"], "tags": "boring, basic, soft, white"},
    {"name": "vanish", "word": "Vanish", "letter": "V", "meaning": "Disappear suddenly", "rap_meaning": "Ghosting, magic trick, making opponents disappear", "syllables": "2 (van-ish)", "pos": "Verb", "synonyms": "Disappear, fade", "antonyms": "Appear", "rhymes": "END: banish, spanish, danish / SLANT: finish / MULTI: replenish", "bars": ["Make the pack vanish, magic without a wand", "Watch me vanish when the sirens wail", "Vanish into thin air, Houdini level escape"], "punchlines": ["Magician imagery", "Ghosting", "Crime scene exit"], "tags": "gone, magic, hide, ghost"},
    {"name": "vanity", "word": "Vanity", "letter": "V", "meaning": "Excessive pride", "rap_meaning": "Vanity plates, looking in the mirror, ego", "syllables": "3 (van-i-ty)", "pos": "Noun", "synonyms": "Pride, ego", "antonyms": "Modesty", "rhymes": "END: sanity, humanity, profanity / SLANT: see / MULTI: calamity", "bars": ["Vanity is my favorite sin, I look too good", "Vanity plates on the foreign, say MYNAME", "Lost your sanity chasing vanity"], "punchlines": ["Devil's Advocate quote", "Mirror mirror on the wall", "Car plates"], "tags": "ego, proud, look, sin"},
    {"name": "vapor", "word": "Vapor", "letter": "V", "meaning": "Gas state", "rap_meaning": "Vaporware (fake product), smoking (vaping), disappearing like smoke", "syllables": "2 (va-por)", "pos": "Noun", "synonyms": "Gas, smoke", "antonyms": "Solid", "rhymes": "END: paper, taper, caper, scraper / SLANT: later / MULTI: skyscraper", "bars": ["Turn you into vapor, evaporated existence", "Chasing that vapor, high off the fumes", "Your promises are vaporware, never materialize"], "punchlines": ["Science states of matter", "Tech slang (vaporware)", "Smoking"], "tags": "smoke, fake, gone, gas"},
    {"name": "vault", "word": "Vault", "letter": "V", "meaning": "Secure room; to jump over", "rap_meaning": "Safe full of money, unreleased music (in the vault), pole vaulting obstacles", "syllables": "1 (vault)", "pos": "Noun/Verb", "synonyms": "Safe, jump", "antonyms": "Open", "rhymes": "END: fault, salt, halt, malt / SLANT: bolt / MULTI: assault", "bars": ["Code to the vault, only select few enter", "Music in the vault could change the charts for years", "Vault over the haters, Olympic height"], "punchlines": ["Bank robbery", "Prince/Tupac vault", "Athletic jump"], "tags": "money, safe, jump, secret"},
    {"name": "vegas", "word": "Vegas", "letter": "V", "meaning": "Las Vegas", "rap_meaning": "Gambling, Sin City, lights, what happens stays there", "syllables": "2 (ve-gas)", "pos": "Noun", "synonyms": "Sin City", "antonyms": "Church", "rhymes": "END: famous, heinous, anus (careful) / SLANT: us / MULTI: contagious", "bars": ["Viva Las Vegas, rolling the fuzzy dice", "Vegas strip lights, blinding the night", "What happens in Vegas, I bring it back home"], "punchlines": ["Gambling metaphors", "Sin City reference", "ELvis reference"], "tags": "city, gamble, party, sin"},
    {"name": "vehicle", "word": "Vehicle", "letter": "V", "meaning": "Transport", "rap_meaning": "The car, or the rap as a vehicle for the message", "syllables": "3 (ve-hi-cle)", "pos": "Noun", "synonyms": "Car, ride", "antonyms": "Foot", "rhymes": "END: miracle, lyrical, spherical / SLANT: circle / MULTI: empirical", "bars": ["Music is the vehicle to get me out the hood", "Foreign vehicle, name I can't pronounce", "Use the beat as a vehicle to transport the dope"], "punchlines": ["Transport metaphor", "Car flex", "Driving the plot"], "tags": "car, drive, method, tool"},
    {"name": "vein", "word": "Vein", "letter": "V", "meaning": "Blood vessel", "rap_meaning": "Ice in veins (clutch), heroin (needle), gold vein", "syllables": "1 (vein)", "pos": "Noun", "synonyms": "Vessel, lode", "antonyms": "Artery", "rhymes": "END: rain, pain, gain, train, brain / SLANT: pen / MULTI: insane", "bars": ["Ice water in my veins, I don't feel pressure", "Tapped a new vein, gold flowing out", "Inject the truth straight in the vein"], "punchlines": ["Clutch gene (ice veins)", "Mining for gold", "Addiction imagery"], "tags": "blood, cold, gold, drug"},
    {"name": "velvet", "word": "Velvet", "letter": "V", "meaning": "Soft fabric", "rap_meaning": "Smooth, luxury, velvet rope (VIP), Red Velvet cake", "syllables": "2 (vel-vet)", "pos": "Noun/Adjective", "synonyms": "Soft, silk", "antonyms": "Sandpaper", "rhymes": "END: helmet, pelvis / SLANT: felt it / MULTI: elvis", "bars": ["Behind the velvet rope, untouchable status", "Smooth like blue velvet, midnight vibes", "Iron hand in a velvet glove, subtle control"], "punchlines": ["VIP club entry", "Texture metaphor", "Dictator quote"], "tags": "soft, rich, vip, clothes"},
    {"name": "vendetta", "word": "Vendetta", "letter": "V", "meaning": "Blood feud", "rap_meaning": "V for Vendetta, personal beef, revenge mission", "syllables": "3 (ven-det-ta)", "pos": "Noun", "synonyms": "Feud, grudge", "antonyms": "Truce", "rhymes": "END: betta, letter, sweater, getter / SLANT: meta / MULTI: beretta", "bars": ["This a personal vendetta, it ain't business", "V for Vendetta, mask on plotting the fall", "Settling the vendetta with interest added"], "punchlines": ["Movie reference (V for Vendetta)", "Italian mob feud", "Holding a grudge"], "tags": "beef, revenge, fight, war"},
    {"name": "vent", "word": "Vent", "letter": "V", "meaning": "Release air; express feelings; duct", "rap_meaning": "Venting on the mic, crawling through vents (heist/sus), releasing pressure", "syllables": "1 (vent)", "pos": "Verb/Noun", "synonyms": "Air, talk", "antonyms": "Suppress", "rhymes": "END: tent, bent, rent, cent, sent / SLANT: mint / MULTI: event", "bars": ["Let me vent for a minute, pressure building up", "Crawling through the air vent, Mission Impossible", "Don't vent to me, I ain't your therapist"], "punchlines": ["Among Us (venting)", "Steam pressure release", "Heist movie"], "tags": "talk, emotional, sneak, air"},
    {"name": "venture", "word": "Venture", "letter": "V", "meaning": "Risky journey or business", "rap_meaning": "Business venture, venture capitalist, taking risks", "syllables": "2 (ven-ture)", "pos": "Noun", "synonyms": "Risk, deal", "antonyms": "Safety", "rhymes": "END: denture, center, enter, mentor / SLANT: winter / MULTI: adventure", "bars": ["Joint venture, 50/50 split on the profit", "Venture into the unknown, fear no evil", "Venture Capitalist flow, investing in myself"], "punchlines": ["Shark Tank style", "Business partnership", "Exploration"], "tags": "business, risk, money, deal"},
    {"name": "verb", "word": "Verb", "letter": "V", "meaning": "Action word", "rap_meaning": "Action not talk, 'verb' as slang for 42 Dugg/reverb?, Action packed", "syllables": "1 (verb)", "pos": "Noun", "synonyms": "Action, word", "antonyms": "Noun", "rhymes": "END: herb, curb, disturb, suburb / SLANT: bird / MULTI: superb", "bars": ["I'm about that action, I'm a verb you a noun", "Hit 'em with the reverb, echo the verb", "Put some respect on my verb, I do things"], "punchlines": ["Grammar metaphor (Action vs Object)", "Doing words", "Active voice"], "tags": "action, grammar, do, word"},
    {"name": "verdict", "word": "Verdict", "letter": "V", "meaning": "Jury decision", "rap_meaning": "Guilty or Not Guilty, final decision, judgment day", "syllables": "2 (ver-dict)", "pos": "Noun", "synonyms": "Judgment, ruling", "antonyms": "Trial", "rhymes": "END: addict, conflict, predict, strict / SLANT: perfect / MULTI: interdict", "bars": ["Waiting on the verdict, sweating in the suit", "Verdict is in: I'm the greatest alive", "Judge and jury, I deliver the verdict myself"], "punchlines": ["Courtroom suspense", "Final judgment", "Self-proclaimed status"], "tags": "law, judge, court, decision"},
    {"name": "verse", "word": "Verse", "letter": "V", "meaning": "Stanza of a poem/song", "rap_meaning": "16 bars, feature price, killing the verse, bible verse", "syllables": "1 (verse)", "pos": "Noun", "synonyms": "Bar, stanza", "antonyms": "Hook", "rhymes": "END: hearse, curse, nurse, purse, worse / SLANT: force / MULTI: universe", "bars": ["Murdered the verse, put the beat in a hearse", "Charge 50k for a verse, price going up", "Chapter and verse, I preach the gospel of hustle"], "punchlines": ["Price of feature", "Killing the beat", "Bible study"], "tags": "music, rap, writing, bars"},
    {"name": "vertical", "word": "Vertical", "letter": "V", "meaning": "Up and down", "rap_meaning": "Going up, vertical leap (basketball), vertical money stacks", "syllables": "3 (ver-ti-cal)", "pos": "Adjective", "synonyms": "Up, tall", "antonyms": "Horizontal", "rhymes": "END: critical, political, analytical / SLANT: miracle / MULTI: surgical", "bars": ["Money vertical, towers touching the sky", "Vertical leap insane, dunking on giants", "Only way is vertical, straight to the top"], "punchlines": ["NBA athleticism", "Graph direction", "Building construction"], "tags": "up, high, jump, direction"},
    {"name": "vest", "word": "Vest", "letter": "V", "meaning": "Sleeveless garment", "rap_meaning": "Bulletproof vest (Kevlar), investing, chest protection", "syllables": "1 (vest)", "pos": "Noun", "synonyms": "Armor, top", "antonyms": "None", "rhymes": "END: chest, test, best, rest, west / SLANT: fast / MULTI: invest", "bars": ["Strap the vest on tight, heavy artillery", "Invest in the vest, protect the heart", "Close the vest, keep the moves secret"], "punchlines": ["Safety/Shootout", "Poker term (play close to vest)", "Investment pun"], "tags": "gun, safe, clothes, armor"},
    {"name": "veteran", "word": "Veteran", "letter": "V", "meaning": "Experienced person; ex-soldier", "rap_meaning": "OG, survived many wars, experienced, respect", "syllables": "3 (vet-er-an)", "pos": "Noun", "synonyms": "Vet, expert", "antonyms": "Rookie", "rhymes": "END: better than, letterman / SLANT: medicine / MULTI: sedan", "bars": ["Veteran moves, rookie mistakes get you killed", "Salute the veteran, I earned my stripes", "War veteran PTSD, flashes of the struggle"], "punchlines": ["Military service", "Experience vs Youth", "Survival"], "tags": "old, expert, respect, war"},
    {"name": "veto", "word": "Veto", "letter": "V", "meaning": "Right to reject", "rap_meaning": "Shutting it down, I say no, boss power", "syllables": "2 (ve-to)", "pos": "Verb/Noun", "synonyms": "Reject, ban", "antonyms": "Approve", "rhymes": "END: keto, mosquito, incognito / SLANT: zero / MULTI: magneto", "bars": ["Veto the decision, I override the board", "Presidential veto power in the streets", "Can't veto my success, it's law"], "punchlines": ["Presidential power", "Boss hierarchy", "Rejection"], "tags": "power, no, boss, law"},
    {"name": "vice", "word": "Vice", "letter": "V", "meaning": "Immoral behavior; tool; Miami Vice", "rap_meaning": "Miami Vice (Crockett/Tubbs), bad habits, grip (vice grip)", "syllables": "1 (vice)", "pos": "Noun", "synonyms": "Sin, grip", "antonyms": "Virtue", "rhymes": "END: ice, nice, price, dice, slice / SLANT: days / MULTI: advice", "bars": ["Miami Vice vibes, white suits and fast boats", "Got you in a vice grip, squeeze till it breaks", "Everyone got a vice, mine is simply winning"], "punchlines": ["Miami Vice TV show", "Tool/Clamp imagery", "Sin/Habit"], "tags": "sin, miami, grip, bad"},
    {"name": "victim", "word": "Victim", "letter": "V", "meaning": "Person harmed", "rap_meaning": "Don't be a victim, playing the victim, predator vs prey", "syllables": "2 (vic-tim)", "pos": "Noun", "synonyms": "Prey, target", "antonyms": "Victor", "rhymes": "END: system, symptom, rhythm / SLANT: him / MULTI: dictum", "bars": ["Don't play the victim when you started the fire", "Another victim of the system, swallowed whole", "Victim mentality keeps you broke"], "punchlines": ["Mindset critique", "Crime scene", "System oppression"], "tags": "weak, crime, sad, lose"},
    {"name": "vigilante", "word": "Vigilante", "letter": "V", "meaning": "Self-appointed law enforcer", "rap_meaning": "Batman style, street justice, taking law into own hands", "syllables": "4 (vig-i-lan-te)", "pos": "Noun", "synonyms": "Avenger, hero", "antonyms": "Cop", "rhymes": "END: panty, aunty, shantyt / SLANT: plenty / MULTI: picante", "bars": ["Vigilante justice, cops arrive too late", "Move like a vigilante in the night shadows", "No judge needed, vigilante execution"], "punchlines": ["Batman/Superhero", "Street justice", "Lawless"], "tags": "justice, street, hero, crime"},
    {"name": "villain", "word": "Villain", "letter": "V", "meaning": "Bad guy", "rap_meaning": "The antagonist, Doom (MF DOOM), being the bad guy for the greater good", "syllables": "2 (vil-lain)", "pos": "Noun", "synonyms": "Criminal, enemy", "antonyms": "Hero", "rhymes": "END: chillin, killin, million, fillin / SLANT: feeling / MULTI: penicillin", "bars": ["Super villain flow, MF DOOM mask on", "Die a hero or live long enough to become the villain", "Villain in your story, hero in mine"], "punchlines": ["Dark Knight quote", "MF DOOM tribute", "Perspective flip"], "tags": "bad, enemy, comic, evil"},
    {"name": "viral", "word": "Viral", "letter": "V", "meaning": "Spreading fast (internet/disease)", "rap_meaning": "Going viral (famous), catch it like a virus, infectious flow", "syllables": "2 (vi-ral)", "pos": "Adjective", "synonyms": "Trending, spreading", "antonyms": "Unknown", "rhymes": "END: spiral, spiral, vinyl / SLANT: final / MULTI: bible", "bars": ["Went viral overnight, price went up today", "Infectious flow going viral, no mask helps", "Don't chase viral moments, chase timeless paper"], "punchlines": ["Internet fame", "Disease metaphor", "Trend chasing"], "tags": "internet, fame, spread, sick"},
    {"name": "virtuoso", "word": "Virtuoso", "letter": "V", "meaning": "Highly skilled artist", "rap_meaning": "Master of the craft, playing the beat perfectly, genius level", "syllables": "4 (vir-tu-o-so)", "pos": "Noun", "synonyms": "Master, genius", "antonyms": "Amateur", "rhymes": "END: torso, more so / SLANT: also / MULTI: espresso", "bars": ["Lyrical virtuoso, painting with words", "Instrumental virtuoso, I play the keys of life", "Watch the virtuoso work, masterclass session"], "punchlines": ["Artistic mastery", "Classically trained flex", "Skill gap"], "tags": "master, skill, art, genius"},
    {"name": "virus", "word": "Virus", "letter": "V", "meaning": "Infectious agent", "rap_meaning": "Sick flow, spreading fast, trojan horse, computer virus", "syllables": "2 (vi-rus)", "pos": "Noun", "synonyms": "Bug, sickness", "antonyms": "Cure", "rhymes": "END: iris, papyrus, cyrus / SLANT: us / MULTI: osiris", "bars": ["Bug in the system, I'm the virus crashing the mainframe", "Spreading like a virus, patient zero", "I'm the virus, you the host, I take over"], "punchlines": ["Computer hacking", "Pandemic imagery", "Infiltration"], "tags": "sick, tech, spread, bad"},
    {"name": "voltage", "word": "Voltage", "letter": "V", "meaning": "Electric potential", "rap_meaning": "High energy, eclectic shock, dangerous power", "syllables": "2 (volt-age)", "pos": "Noun", "synonyms": "Power, juice", "antonyms": "Ground", "rhymes": "END: dosage, postage / SLANT: age / MULTI: hostage", "bars": ["High voltage, keep your hands off the fence", "Amp up the voltage, fry the circuits", "Voltage flowing through the mic, electric chair"], "punchlines": ["Electricity warning", "Shock value", "Power level"], "tags": "power, energy, shock, danger"},
    {"name": "vulture", "word": "Vulture", "letter": "V", "meaning": "Bird that eats dead things", "rap_meaning": "People waiting for you to fail, label execs, picking the bones", "syllables": "2 (vul-ture)", "pos": "Noun", "synonyms": "Scavenger", "antonyms": "Eagle", "rhymes": "END: culture, sculpture / SLANT: future / MULTI: agriculture", "bars": ["Culture vulture, stealing our style for profit", "Vultures circling, waiting for my demise", "Pick the bones clean like a hungry vulture"], "punchlines": ["Culture Vulture phrase", "Scavenger behavior", "Circling enemies"], "tags": "bird, thief, death, enemy"},
]

def create_word(word_data):
    letter = word_data["letter"]
    letter_path = Path(BASE_PATH) / letter
    words_base_path = letter_path / "01_Words"
    words_base_path.mkdir(parents=True, exist_ok=True)
    word_folder = words_base_path / word_data["name"]
    word_folder.mkdir(exist_ok=True)

    template = f"""# WORD: {word_data["word"]}

## Meaning (plain):
{word_data["meaning"]}

## Rap meaning (how I'd say it):
{word_data["rap_meaning"]}

## Syllables:
{word_data["syllables"]}

## Part of speech:
{word_data["pos"]}

## Synonyms:
{word_data["synonyms"]}

## Antonyms:
{word_data["antonyms"]}

## Rhyme ideas (end / slant / multi):
{word_data["rhymes"]}

## 3 bar-ready examples:
1. {word_data["bars"][0]}
2. {word_data["bars"][1]}
3. {word_data["bars"][2]}

## 3 punchline angles:
1. {word_data["punchlines"][0]}
2. {word_data["punchlines"][1]}
3. {word_data["punchlines"][2]}

## Tags:
{word_data["tags"]}
"""
    word_file = word_folder / "word.md"
    word_file.write_text(template, encoding='utf-8')
    print(f"[+] Created: {letter}/{word_data['name']}")

def main():
    print(f"Adding 40 remaining V words...")
    for word_data in WORDS:
        create_word(word_data)
    print(f"Done with V.")

if __name__ == "__main__":
    main()
