#!/usr/bin/env python3
import os
import sys
from pathlib import Path

if sys.platform == 'win32':
    sys.stdout.reconfigure(encoding='utf-8')

BASE_PATH = r"C:\Users\JaZeR\OneDrive\Desktop\2026 → JaZeR Mainframe\2026 → JaZeR Master Flow Knowledge Hub\Rap_Dictionary_Master_Hub"

# 40 New Y Words
WORDS = [
    {"name": "yacht", "word": "Yacht", "letter": "Y", "meaning": "A medium-sized sailing boat equipped for cruising or racing", "rap_meaning": "Ultimate luxury, success on water, wealthy lifestyle status", "syllables": "1 (yacht)", "pos": "Noun", "synonyms": "Boat, vessel, ship", "antonyms": "Dinghy, rowboat", "rhymes": "END: knot, hot, shot, plot, spot / SLANT: bought / MULTI: astronaut", "bars": ["Parking the yacht in the harbor of dreams", "From a canoe to a yacht, levels to this stream", "Yacht party, white linen, strictly business"], "punchlines": ["Lil Yachty reference", "Size matters (boat vs yacht)", "International waters law"], "tags": "luxury, boat, rich, water"},
    {"name": "yak", "word": "Yak", "letter": "Y", "meaning": "Cognac (slang); to talk continuously", "rap_meaning": "Drinking Hennessy (Yak), or someone talking too much (yapping)", "syllables": "1 (yak)", "pos": "Noun/Verb", "synonyms": "Cognac, talk, chatter", "antonyms": "Silence, water", "rhymes": "END: back, stack, track, black, sack / SLANT: check / MULTI: cadillac", "bars": ["Sipping on the Yak, feeling like a don", "You just yak yak yak, but say nothing", "Pour out a little Yak for the homies gone"], "punchlines": ["Hennessy abbreviation", "Chatterbox insult", "Animal pun"], "tags": "drink, alcohol, talk, slang"},
    {"name": "yam", "word": "Yam", "letter": "Y", "meaning": "Sweet potato; slang for drugs/money", "rap_meaning": "The Yams (power/drugs/money), or Thanksgiving food", "syllables": "1 (yam)", "pos": "Noun", "synonyms": "Potato, sweet-potato", "antonyms": "None", "rhymes": "END: ham, scam, dam, jam, slam / SLANT: them / MULTI: telegram", "bars": ["I got the yams, supplying the whole street", "Thanksgiving feast, pass the candied yams", "The yams is the power, ask Kendrick"], "punchlines": ["Kendrick Lamar 'King Kunta' reference", "Drug slang", "Food soul food"], "tags": "food, drugs, slang, power"},
    {"name": "yank", "word": "Yank", "letter": "Y", "meaning": "To pull with a jerk", "rap_meaning": "Viking chains, stealing, pulling someone's card", "syllables": "1 (yank)", "pos": "Verb", "synonyms": "Pull, jerk, snatch", "antonyms": "Push", "rhymes": "END: bank, rank, tank, shank, dank / SLANT: think / MULTI: blank", "bars": ["Yank the chain off your neck, gimme that", "Don't yank my chain, tell me the truth", "Yank you out the game like a bad tooth"], "punchlines": ["Chain snatching", "Dental extraction metaphor", "Sudden removal"], "tags": "steal, pull, aggressive, chain"},
    {"name": "yankee", "word": "Yankee", "letter": "Y", "meaning": "New York Yankees; American", "rap_meaning": "NY hat (fitted), winning team, Derek Jeter status", "syllables": "2 (yan-kee)", "pos": "Noun", "synonyms": "Ny, american", "antonyms": "Red Sox", "rhymes": "END: cranky, lanky, hanky / SLANT: thank ye / MULTI: spanky", "bars": ["Yankee fitted low, brim covering eyes", "Hit a home run in Yankee stadium usage", "More rings than a Yankee, dynasty flow"], "punchlines": ["Hat fashion (brim/no brim)", "Baseball reference", "New York representation"], "tags": "ny, baseball, hat, win"},
    {"name": "yap", "word": "Yap", "letter": "Y", "meaning": "To talk noisily", "rap_meaning": "Talking snitch, mouth running, annoying noise", "syllables": "1 (yap)", "pos": "Verb", "synonyms": "Talk, chatter, bark", "antonyms": "Silence", "rhymes": "END: trap, map, cap, lap, nap / SLANT: step / MULTI: mishap", "bars": ["Shut your yap before you get clapped", "All you do is yap, where the action at?", "Small dogs yap, big dogs bite"], "punchlines": ["Dog barking metaphor", "Snitching warning", "Empty talk"], "tags": "talk, annoying, snitch, noise"},
    {"name": "yardstick", "word": "Yardstick", "letter": "Y", "meaning": "Standard for comparison", "rap_meaning": "The standard of measurement, measuring success, setting the bar", "syllables": "2 (yard-stick)", "pos": "Noun", "synonyms": "Standard, measure", "antonyms": "Guess", "rhymes": "END: hard brick, card trick / SLANT: quick / MULTI: lunatic", "bars": ["I'm the yardstick everyone measured against", "Short money don't reach the yardstick marks", "Broke the yardstick, I'm off the charts"], "punchlines": ["Measurement tool", "Setting the standard", "Size comparison"], "tags": "measure, standard, rule, compare"},
    {"name": "yarn", "word": "Yarn", "letter": "Y", "meaning": "Spun thread; a long story", "rap_meaning": "Spinning stories (lies), fabricating tales, knitting a plot", "syllables": "1 (yarn)", "pos": "Noun", "synonyms": "Story, tale, thread", "antonyms": "Fact", "rhymes": "END: barn, darn, tarn / SLANT: born, corn / MULTI: forewarn", "bars": ["Spinning a yarn to the judge, fairy tales", "Unravel the yarn, truth comes out", "Fabricated yarn, your life is fiction"], "punchlines": ["Knitting/Spinning metaphor", "Lying/Storytelling", "Cat toy imagery"], "tags": "story, lie, thread, fake"},
    {"name": "yawn", "word": "Yawn", "letter": "Y",
    "meaning": "Involuntary opening of mouth due to tiredness/boredom", "rap_meaning": "Boring competition, sleeping on opponents, easy work", "syllables": "1 (yawn)", "pos": "Verb", "synonyms": "Sleep, bore", "antonyms": "Excite", "rhymes": "END: dawn, lawn, pawn, drawn / SLANT: gone / MULTI: leprechaun", "bars": ["Make me yawn, your flow is a sedative", "Yawn at the threat, I ain't even flinch", "Woke up with a yawn and made a million"], "punchlines": ["Boredom insult", "Morning routine flex", "Disrespectful reaction"], "tags": "boring, sleep, easy, diss"},
    {"name": "yea", "word": "Yea", "letter": "Y", "meaning": "Yes", "rap_meaning": "Affirmation, yea yea (adlib), agreement", "syllables": "1 (yea)", "pos": "Adverb", "synonyms": "Yes, aye", "antonyms": "Nay", "rhymes": "END: play, day, say, way / SLANT: yeah / MULTI: okay", "bars": ["Vote yea for the money, nay for the broke", "Yea though I walk through the valley of death", "Yea yea, heard it all before"], "punchlines": ["Bible quote intro", "Parliament voting", "Dismissive adlib"], "tags": "yes, agree, adlib, bible"},
    {"name": "yeah", "word": "Yeah", "letter": "Y", "meaning": "Yes (casual)", "rap_meaning": "Universal filler, hype adlib (Lil Jon), flows better than yes", "syllables": "1 (yeah)", "pos": "Adverb", "synonyms": "Yes, yup", "antonyms": "Nah", "rhymes": "END: air, fair, pear / SLANT: here / MULTI: nightmare", "bars": ["Yeah! Like Lil Jon in the early 2000s", "Yeah I said it, what you gonna do?", "Hell yeah, we taking over the summer"], "punchlines": ["Lil Jon reference", "Assertion of truth", "Celebration"], "tags": "adlib, hype, yes, loud"},
    {"name": "yearbook", "word": "Yearbook", "letter": "Y", "meaning": "Annual publication of school photos", "rap_meaning": "Remembering the past, most likely to succeed, class photos", "syllables": "2 (year-book)", "pos": "Noun", "synonyms": "Annual, record", "antonyms": "None", "rhymes": "END: look, cook, hook, crook / SLANT: buck / MULTI: checkbook", "bars": ["Check the yearbook, I was voted most likely to ball", "Not in the yearbook, was out in the hall grinding", "Look at my yearbook photo, saw the vision in the eyes"], "punchlines": ["High school nostalgia", "Superlatives (Most Likely To...)", "Transformation comparison"], "tags": "school, memory, past, photo"},
    {"name": "yeast", "word": "Yeast", "letter": "Y", "meaning": "Fungus used to make bread rise", "rap_meaning": "Rising to the top, getting bread (money), infection (insult)", "syllables": "1 (yeast)", "pos": "Noun", "synonyms": "Leaven, fungus", "antonyms": "Flat", "rhymes": "END: beast, east, feast, least, priest / SLANT: best, chest / MULTI: deceased", "bars": ["Got the yeast in the dough, watch the money rise", "Rise like yeast, heat makes me expand", "You a yeast infection, irritating the game"], "punchlines": ["Baking bread metaphor", "Money rising", "Medical insult"], "tags": "money, rise, cook, insult"},
    {"name": "yelp", "word": "Yelp", "letter": "Y", "meaning": "Short sharp cry; review app", "rap_meaning": "Cry for help, snitching, or giving bad reviews to haters", "syllables": "1 (yelp)", "pos": "Noun/Verb",
    "synonyms": "Cry, bark", "antonyms": "Roar", "rhymes": "END: help, kelp, whelp / SLANT: felt / MULTI: scalp", "bars": ["Give you a 1-star on Yelp, service was trash", "Make 'em yelp when the pressure applies", "Don't yelp for help now, you chose this"], "punchlines": ["App review metaphor", "Dog pain noise", "Cry for help"], "tags": "app, review, cry, pain"},
    {"name": "yen", "word": "Yen", "letter": "Y", "meaning": "Japanese currency; a longing", "rap_meaning": "Foreign money (Japan), deep desire/craving", "syllables": "1 (yen)", "pos": "Noun", "synonyms": "Money, craving", "antonyms": "None", "rhymes": "END: zen, ten, men, pen, den / SLANT: in / MULTI: again", "bars": ["Stacking Yen in Tokyo, global transactions", "Got a yen for the win, addicted to gold", "Converting Dollars to Yen, international spend"], "punchlines": ["Currency exchange", "Addiction/Craving", "Japan connection"], "tags": "money, foreign, desire, japan"},
    {"name": "yeoman", "word": "Yeoman", "letter": "Y", "meaning": "A servant; hard worker", "rap_meaning": "Doing the heavy lifting (yeoman's work), foundational grinder", "syllables": "2 (yeo-man)", "pos": "Noun", "synonyms": "Worker, servant", "antonyms": "King", "rhymes": "END: omen, roman, showman / SLANT: human / MULTI: abdomen", "bars": ["Did the yeoman's work, built the foundation", "Not a yeoman, I'm the lord of the land", "Yeoman effort, carried the whole team on my back"], "punchlines": ["Medieval hierarchy", "Hard work credit", "Carrying the load"], "tags": "work, grind, serve, history"},
    {"name": "yes", "word": "Yes", "letter": "Y", "meaning": "Affirmative", "rap_meaning": "Positivity, agreement, success signal", "syllables": "1 (yes)", "pos": "Adverb", "synonyms": "Yea, affirmative", "antonyms": "No", "rhymes": "END: bless, chess, mess, less, dress / SLANT: ace / MULTI: success", "bars": ["Answer is yes, I am the greatest", "No turning back, just yes to the check", "Say yes to the dress? Nah, yes to the necklace"], "punchlines": ["Wedding show reference", "Binary choice (Yes/No)", "Affirmation"], "tags": "agree, positive, answer, simple"},
    {"name": "yeti", "word": "Yeti", "letter": "Y", "meaning": "Abominable Snowman", "rap_meaning": "Cold hearted, ice (jewelry), monster, rare sighting", "syllables": "2 (yet-i)", "pos": "Noun", "synonyms": "Monster, snowman", "antonyms": "None", "rhymes": "END: jetty, petty, sweaty, confetti / SLANT: ready / MULTI: spaghetti", "bars": ["Wrist cold like a Yeti in the Himalayas", "Rare sighting like the Yeti, I barely come out", "Abominable flow, call me the Yeti"], "punchlines": ["Ice/Jewelry coldness", "Monster metaphor", "Mythical creature"], "tags": "monster, cold, ice, rare"},
    {"name": "yin", "word": "Yin", "letter": "Y", "meaning": "Dark/passive principle in Chinese philosophy", "rap_meaning": "Dark side, shadow, feminine energy, balance", "syllables": "1 (yin)", "pos": "Noun", "synonyms": "Dark, moon", "antonyms": "Yang", "rhymes": "END: skin, sin, win, pin / SLANT: seen / MULTI: begin", "bars": ["I got a dark side, that's the Yin taking over", "Need the Yin to my Yang, balance the power", "Sitting in the Yin, comfortable in shadows"], "punchlines": ["Yin and Yang balance", "Darkness appreciation", "Philosophy"], "tags": "dark, balance, asian, shadow"},
    {"name": "yin-yang", "word": "Yin-yang", "letter": "Y", "meaning": "Two principles, one negative, dark, and feminine (yin) and one positive, bright, and masculine (yang)", "rap_meaning": "Duality, good and evil, love and hate, balance", "syllables": "2 (yin-yang)", "pos": "Noun", "synonyms": "Balance, duality", "antonyms": "Chaos", "rhymes": "END: bang, gang, slang, hang / SLANT: thing / MULTI: boomerang", "bars": ["Life is Yin-Yang, pain comes with the pleasure", "Yin-Yang twins energy, get low in the club", "Perfect balance like Yin-Yang symbol"], "punchlines": ["Yin Yang Twins group reference", "Duality of man", "Black and white symbol"], "tags": "balance, dual, symbol, philosophy"},
    {"name": "yo", "word": "Yo", "letter": "Y", "meaning": "Exclamation used to get attention", "rap_meaning": "Street greeting, hey, look here, classic hiphop start", "syllables": "1 (yo)", "pos": "Exclamation", "synonyms": "Hey, look", "antonyms": "Bye", "rhymes": "END: go, flow, slow, low, know / SLANT: you / MULTI: chateau", "bars": ["Yo, listen up, class in session", "I said Yo! Pay attention to the man", "Yo yo yo, check the microphone check"], "punchlines": ["MTV Raps intro style", "Getting attention", "Simple greeting"], "tags": "greeting, slang, attention, start"},
    {"name": "yo-yo", "word": "Yo-yo", "letter": "Y", "meaning": "Toy on a string; vary fluctuatingly", "rap_meaning": "Ups and downs, coming back around, treating people like toys", "syllables": "2 (yo-yo)", "pos": "Noun", "synonyms": "Toy, fluctuate", "antonyms": "Steady", "rhymes": "END: mojo, dojo, logo / SLANT: go / MULTI: slo-mo", "bars": ["Life like a yo-yo, ups and downs but I spin it", "Got you on a string like a yo-yo, puppet master", "Yo-yo diet on the money, fat then skinny"], "punchlines": ["String control", "Up and down movement", "Around the world trick"], "tags": "toy, control, fluctuate, up-down"},
    {"name": "yoga", "word": "Yoga", "letter": "Y", "meaning": "Exercise for flexibility/meditation", "rap_meaning": "Flexible with the schedule/money, stretching the truth, finding peace", "syllables": "2 (yo-ga)", "pos": "Noun", "synonyms": "Stretch, exercise", "antonyms": "Stiff", "rhymes": "END: toga, soda / SLANT: over / MULTI: pagoda", "bars": ["Stretching money like it's yoga class", "Doing yoga on the beat, flexible flow", "She doing yoga positions, my peace of mind"], "punchlines": ["Financial stretching", "Sexual innuendo", "Mental focus"], "tags": "stretch, peace, flexible, exercise"},
    {"name": "yogi", "word": "Yogi", "letter": "Y", "meaning": "One who practices yoga; Yogi Bear", "rap_meaning": "Wise master, stealing picnic baskets (looting), bear mode", "syllables": "2 (yo-gi)", "pos": "Noun", "synonyms": "Master, bear", "antonyms": "Student", "rhymes": "END: bogie, stogie, fogey / SLANT: doggy / MULTI: emoji", "bars": ["Smarter than the average bear, call me Yogi", "Lighting up a stogie, meditating like a Yogi", "Yogi Berra wisdom, it ain't over till it's over"], "punchlines": ["Cartoon reference (Yogi Bear)", "Wisdom (Yogi Berra)", "Spiritual master"], "tags": "wise, bear, cartoon, master"},
    {"name": "yogurt", "word": "Yogurt", "letter": "Y", "meaning": "Semisolid sour food", "rap_meaning": "Soft, culture (literally), white/creamy substance", "syllables": "2 (yo-gurt)", "pos": "Noun", "synonyms": "Dairy, culture", "antonyms": "Rock", "rhymes": "END: hurt, shirt, dirt, skirt / SLANT: desert / MULTI: convert", "bars": ["You soft like frozen yogurt, sweet and melty", "Got more culture than greek yogurt", "White yogurt whip, creamy interior"], "punchlines": ["Soft insult", "Bacteria/Culture pun", "Car paint job"], "tags": "soft, food, culture, white"},
    {"name": "yolk", "word": "Yolk", "letter": "Y", "meaning": "Yellow part of an egg", "rap_meaning": "The center, the gold, breaking eggs to make omelet, sun", "syllables": "1 (yolk)", "pos": "Noun", "synonyms": "Yellow, center", "antonyms": "White", "rhymes": "END: folk, soak, cloak, oak / SLANT: look / MULTI: provoke", "bars": ["Crack the egg get the yolk, gold inside", "Sun looking like a yolk in the sky frying", "Separate the white from the yolk, keep it pure"], "punchlines": ["Cooking metaphor", "Color of gold", "Core/Center"], "tags": "yellow, gold, food, center"},
    {"name": "yonder", "word": "Yonder", "letter": "Y", "meaning": "At some distance", "rap_meaning": "Far away, the future, over there, looking ahead", "syllables": "2 (yon-der)", "pos": "Adverb", "synonyms": "There, distant", "antonyms": "Here", "rhymes": "END: wander, ponder, squander / SLANT: thunder / MULTI: responder", "bars": ["Look over yonder, better days coming", "Wild blue yonder, flying private jets", "From here to yonder, my territory expands"], "punchlines": ["Old western speak", "Distance visualization", "Future looking"], "tags": "distance, far, future, location"},
    {"name": "you", "word": "You", "letter": "Y", "meaning": "Pronoun", "rap_meaning": "Direct address, pointing the finger, it's about YOU not me", "syllables": "1 (you)", "pos": "Pronoun", "synonyms": "Thou, ya", "antonyms": "Me, I", "rhymes": "END: do, blue, shoe, crew, new / SLANT: view / MULTI: voodoo", "bars": ["It ain't me, it's YOU that's the problem", "YOU got to want it more than you want air", "Looking in the mirror, only enemy is YOU"], "punchlines": ["Soulja Boy reference (YOOOUUU)", "Self-reflection", "Accusation"], "tags": "pronoun, direct, person, address"},
    {"name": "youngan", "word": "Youngan", "letter": "Y", "meaning": "Young person (slang)", "rap_meaning": "Young shooter, protege, little homie, rookie", "syllables": "2 (young-an)", "pos": "Noun", "synonyms": "Kid, rookie", "antonyms": "OG", "rhymes": "END: dungeon, sponge in, lung in / SLANT: run / MULTI: onion", "bars": ["Tell the youngan put the gun away", "Youngan got potential but he lacks discipline", "Raised the youngan to be a boss not a worker"], "punchlines": ["Mentorship", "Street hierarchy", "Age gap"], "tags": "youth, slang, kid, rookie"},
    {"name": "youngster", "word": "Youngster", "letter": "Y", "meaning": "A child or young person", "rap_meaning": "Kid, inexperienced, energetic new generation", "syllables": "2 (young-ster)", "pos": "Noun", "synonyms": "Child, kid", "antonyms": "Elder", "rhymes": "END: dumpster, hamster / SLANT: monster / MULTI: gangster", "bars": ["Listen here youngster, respect the architects", "Youngster moving reckless, gonna crash out", "I was a youngster with a dream and a scheme"], "punchlines": ["OG advice", "Experience vs Youth", "Throwback memory"], "tags": "youth, kid, age, rookie"},
    {"name": "your", "word": "Your", "letter": "Y", "meaning": "Belonging to you", "rap_meaning": "Ownership, claiming it, your fault vs mine", "syllables": "1 (your)", "pos": "Adjective", "synonyms": "Thy", "antonyms": "My", "rhymes": "END: sure, pure, tour, cure, lure / SLANT: more / MULTI: endure", "bars": ["Your loss is my gain, simple math", "Your city? Nah it's my city now", "Claim your destiny before it fades"], "punchlines": ["Possession takeover", "Responsibility", "Direct address"], "tags": "own, possess, pronoun, address"},
    {"name": "youth", "word": "Youth", "letter": "Y", "meaning": "Period of being young", "rap_meaning": "Early days, beauty, innocence lost, the new generation", "syllables": "1 (youth)", "pos": "Noun", "synonyms": "Young, childhood", "antonyms": "Age", "rhymes": "END: truth, booth, tooth, ruth / SLANT: roof / MULTI: uncouth", "bars": ["Fountain of youth in the liquor bottle", "Wasted youth chasing pennies", "Listen to the youth, they know the future"], "punchlines": ["Fountain of youth myth", "Wisdom vs Youth", "Sound of the youth"], "tags": "age, young, future, time"},
    {"name": "your-highness", "word": "Your-Highness", "letter": "Y", "meaning": "Title of respect for royalty", "rap_meaning": "King status, demand respect, stoned (highness)", "syllables": "2 (your-high-ness)", "pos": "Noun", "synonyms": "Majesty, king", "antonyms": "Peasant", "rhymes": "END: blindness, kindness, dryness / SLANT: finest / MULTI: minus", "bars": ["Address me as Your Highness when you speak", "Achieved a new level of Highness, cloud nine", "Bow down to Your Highness, kiss the ring"], "punchlines": ["Royalty title", "Weed pun (High-ness)", "Ego flex"], "tags": "king, royalty, high, respect"},
    {"name": "yowl", "word": "Yowl", "letter": "Y", "meaning": "Loud wailing cry", "rap_meaning": "Cat cry, painful scream, wolf howl", "syllables": "1 (yowl)", "pos": "Verb",
    "synonyms": "Howl, cry", "antonyms": "Purr", "rhymes": "END: owl, foul, towel, cowl, growl / SLANT: ball / MULTI: bowel", "bars": ["Make the engine yowl down the strip", "Alley cat yowl, fight in the night", "Don't yowl when you get scratched"], "punchlines": ["Car engine sound", "Cat fight", "Pain response"], "tags": "sound, cry, loud, animal"},
    {"name": "yuletide", "word": "Yuletide", "letter": "Y", "meaning": "Christmas season", "rap_meaning": "Winter season, gifts, cold weather, family time", "syllables": "2 (yule-tide)", "pos": "Noun", "synonyms": "Christmas", "antonyms": "Summer", "rhymes": "END: ride, side, slide, glide / SLANT: died / MULTI: divide", "bars": ["Yuletide blessings, counting up the bag", "Cold as Yuletide without a coat", "Bring the Yuletide cheer to the block"], "punchlines": ["Christmas reference", "Season of giving", "Winter cold"], "tags": "holiday, cold, gift, season"},
    {"name": "yummy", "word": "Yummy", "letter": "Y", "meaning": "Delicious", "rap_meaning": "Good food, looking good (sexual), sweet life", "syllables": "2 (yum-my)", "pos": "Adjective", "synonyms": "Tasty, good", "antonyms": "Gross", "rhymes": "END: tummy, dummy, mummy, gummy / SLANT: money / MULTI: crummy", "bars": ["Life is yummy, eat it up with a spoon", "Yummy mummy looking at me in the coupe", "Justin Bieber Yummy flow, pop appeal"], "punchlines": ["Bieber song reference", "Taste metaphor", "Sexual slang"], "tags": "food, good, taste, sexy"},
    {"name": "yuppie", "word": "Yuppie", "letter": "Y", "meaning": "Young urban professional", "rap_meaning": "Corporate sellout, rich kid, gentrification agent", "syllables": "2 (yup-pie)", "pos": "Noun", "synonyms": "Preppy, pro", "antonyms": "Thug", "rhymes": "END: puppy, guppy / SLANT: happy / MULTI: disrupt me", "bars": ["Neighborhood changed, full of yuppies now", "Yuppie money spends the same as street money", "Suit like a yuppie, heart like a killer"], "punchlines": ["Gentrification critique", "Appearance vs Reality", "American Psycho reference"], "tags": "rich, class, gentrification, fake"},
    {"name": "yurt", "word": "Yurt", "letter": "Y", "meaning": "Circular tent", "rap_meaning": "Glamping, nomadic lifestyle, weird flex, remote location", "syllables": "1 (yurt)", "pos": "Noun", "synonyms": "Tent, hut", "antonyms": "Mansion", "rhymes": "END: hurt, dirt, shirt, skirt / SLANT: heart / MULTI: desert", "bars": ["Camping in a yurt, connect with the earth", "From the dirt to a yurt to a castle", "Nomad style, set up the yurt anywhere"], "punchlines": ["Genghis Khan imagery", "Unique housing flex", "Nature connection"], "tags": "house, travel, nature, tent"},
    {"name": "yourself", "word": "Yourself", "letter": "Y", "meaning": "Reflexive pronoun", "rap_meaning": "Self-reliance, only you can save you, check yourself", "syllables": "2 (your-self)", "pos": "Pronoun", "synonyms": "You", "antonyms": "Others", "rhymes": "END: shelf, elf, wealth, health / SLANT: self / MULTI: itself", "bars": ["Better check yourself before you wreck yourself", "Love yourself or nobody else will", "Do it yourself, DIY millionaire"], "punchlines": ["Ice Cube reference", "Self-love", "Independence"], "tags": "self, pronoun, alone, check"},
]

def create_word(word_data):
    letter = word_data["letter"]
    letter_path = Path(BASE_PATH) / letter
    words_base_path = letter_path / "01_Words"
    words_base_path.mkdir(parents=True, exist_ok=True)
    word_folder = words_base_path / word_data["name"]
    word_folder.mkdir(exist_ok=True)

    template = f"""# WORD: {word_data["word"]}

## Meaning (plain):
{word_data["meaning"]}

## Rap meaning (how I'd say it):
{word_data["rap_meaning"]}

## Syllables:
{word_data["syllables"]}

## Part of speech:
{word_data["pos"]}

## Synonyms:
{word_data["synonyms"]}

## Antonyms:
{word_data["antonyms"]}

## Rhyme ideas (end / slant / multi):
{word_data["rhymes"]}

## 3 bar-ready examples:
1. {word_data["bars"][0]}
2. {word_data["bars"][1]}
3. {word_data["bars"][2]}

## 3 punchline angles:
1. {word_data["punchlines"][0]}
2. {word_data["punchlines"][1]}
3. {word_data["punchlines"][2]}

## Tags:
{word_data["tags"]}
"""
    word_file = word_folder / "word.md"
    word_file.write_text(template, encoding='utf-8')
    print(f"[+] Created: {letter}/{word_data['name']}")

def main():
    print(f"Adding 40 remaining Y words...")
    for word_data in WORDS:
        create_word(word_data)
    print(f"Done with Y.")

if __name__ == "__main__":
    main()
