#!/usr/bin/env python3
import os
import sys
from pathlib import Path

if sys.platform == 'win32':
    sys.stdout.reconfigure(encoding='utf-8')

BASE_PATH = r"C:\Users\JaZeR\OneDrive\Desktop\2026 → JaZeR Mainframe\2026 → JaZeR Master Flow Knowledge Hub\Rap_Dictionary_Master_Hub"

# 40 New X Words
WORDS = [
    {"name": "x-act", "word": "X-act", "letter": "X", "meaning": "Exact (stylized)", "rap_meaning": "Precision, exact amount, on point", "syllables": "2 (x-act)", "pos": "Adjective", "synonyms": "Exact, precise", "antonyms": "Vague", "rhymes": "END: fact, pact, tact, stack / SLANT: back, track / MULTI: contract, impact", "bars": ["Give me the X-act amount, no shorts", "Timing X-act, I never miss a beat", "X-act science how I whip the pot"], "punchlines": ["Scientific precision", "Money counting", "Stylized spelling flex"], "tags": "slang, precision, money, exact"},
    {"name": "x-citement", "word": "X-citement", "letter": "X", "meaning": "Excitement (stylized)", "rap_meaning": "Hype, thrill, huge energy", "syllables": "3 (x-cite-ment)", "pos": "Noun", "synonyms": "Thrill, hype", "antonyms": "Boredom", "rhymes": "END: indictment, enlightenment / SLANT: payment / MULTI: incitement", "bars": ["Feel the X-citement when I step in the room", "Providing X-citement for the bored masses", "X-citement levels critical, roof blowing off"], "punchlines": ["Crowd control", "Adrenaline levels", "Stylized spelling"], "tags": "slang, energy, hype, thrill"},
    {"name": "x-clusive", "word": "X-clusive", "letter": "X", "meaning": "Exclusive (stylized)", "rap_meaning": "VIP only, rare, one of a kind, not for everyone", "syllables": "3 (x-clu-sive)", "pos": "Adjective", "synonyms": "Rare, private, vip", "antonyms": "Public, common", "rhymes": "END: elusive, abusive, intrusive / SLANT: music / MULTI: conclusive", "bars": ["X-clusive party, your name ain't on the list", "Drop X-clusive tracks, never leaked", "Lifestyle X-clusive, ordinary people can't view"], "punchlines": ["VIP rope metaphor", "Leaked music vs Official", "Rarity value"], "tags": "slang, vip, rare, rich"},
    {"name": "x-husband", "word": "X-husband", "letter": "X", "meaning": "Former husband", "rap_meaning": "The past, someone cut off, alimony payments", "syllables": "3 (x-hus-band)", "pos": "Noun", "synonyms": "Ex", "antonyms": "Husband", "rhymes": "END: band, land, sand, hand / SLANT: end / MULTI: command, expand", "bars": ["Treat you like an X-husband, you cut off", "Drama like an X-husband asking for checks", "No X-husband energy, I move onto the next"], "punchlines": ["Divorce court", "Past relationships", "Cutting ties"], "tags": "relationship, ex, past, drama"},
    {"name": "x-wife", "word": "X-wife", "letter": "X", "meaning": "Former wife", "rap_meaning": "Costly mistakes, bitter past, or freedom", "syllables": "2 (x-wife)", "pos": "Noun", "synonyms": "Ex", "antonyms": "Wife", "rhymes": "END: life, knife, strife / SLANT: safe / MULTI: afterlife", "bars": ["Cost me more than an X-wife settlement", "Bitter like an X-wife scorned", "New chick bad, X-wife mad"], "punchlines": ["Alimony jokes", "Kanye/Kim references", "Freedom cost"], "tags": "relationship, ex, money, drama"},
    {"name": "x-games", "word": "X-Games", "letter": "X", "meaning": "Extreme sports event", "rap_meaning": "Doing extreme stunts, living dangerously, high risk", "syllables": "2 (x-games)", "pos": "Noun", "synonyms": "Stunts, danger", "antonyms": "Safety", "rhymes": "END: names, flames, frames / SLANT: same / MULTI: war games", "bars": ["Life is X-Games, I'm doing flips over the edge", "No safety gear, strictly X-Games mode", "Gold medal in the X-Games of the trap"], "punchlines": ["Tony Hawk/Skateboarding", "Extreme risk taking", "Medals/Winning"], "tags": "sports, extreme, danger, stunts"},
    {"name": "x-files", "word": "X-Files", "letter": "X", "meaning": "TV show about paranormal; unsolved cases", "rap_meaning": "Secret information, supernatural events, aliens, unsolved mysteries", "syllables": "2 (x-files)", "pos": "Noun", "synonyms": "Mystery, secrets", "antonyms": "News", "rhymes": "END: miles, piles, styles, smiles / SLANT: wild / MULTI: profiles", "bars": ["My life belongs in the X-Files, unexplained phenomena", "Open the X-Files, reveal the truth about the game", "X-Files classified, you don't feature clearanace"], "punchlines": ["Mulder and Scully", "Alien/UFO conspiracy", "Government secrets"], "tags": "mystery, secret, alien, tv"},
    {"name": "x-men", "word": "X-Men", "letter": "X", "meaning": "Marvel mutant superhero team", "rap_meaning": "Mutants, having superpowers, being evolved/different, team of shooters", "syllables": "2 (x-men)", "pos": "Noun", "synonyms": "Mutants, heroes", "antonyms": "Humans", "rhymes": "END: pen, ten, den, when / SLANT: in / MULTI: again, amen", "bars": ["Squad full of mutants like the X-Men", "Wolverine clocks, X-Men professor mind", "We the new X-Men, evolved past you humans"], "punchlines": ["Wolverine claws", "Professor X mind control", "Magneto metal control"], "tags": "hero, squad, mutant, power"},
    {"name": "x-mas", "word": "X-mas", "letter": "X", "meaning": "Christmas abbreviation", "rap_meaning": "Gifting, freezing cold (December), Grinch vibes, family", "syllables": "2 (x-mas)", "pos": "Noun", "synonyms": "Christmas, holiday", "antonyms": "Summer", "rhymes": "END: pass, glass, grass, class / SLANT: fast / MULTI: trespass", "bars": ["Every day is X-mas when you ball like this", "Cold shoulder like X-mas eve", "Bag full of gifts, Santa Claus on X-mas"], "punchlines": ["Santa sack (money bag)", "Grinch stealing X-mas", "Gifting season"], "tags": "holiday, gifts, cold, celebrate"},
    {"name": "x-post", "word": "X-post", "letter": "X", "meaning": "Cross-post (internet slang)", "rap_meaning": "Double dipping, spreading the word across hoods/platforms", "syllables": "2 (x-post)", "pos": "Verb", "synonyms": "Share, spread", "antonyms": "Delete", "rhymes": "END: ghost, roast, toast, coast / SLANT: most / MULTI: signpost", "bars": ["X-post the content, viral on all blocks", "Don't X-post my business if you ain't involved", "Networking heavy, X-post the connections"], "punchlines": ["Social media viral strategy", "Crossing territories", "Information spread"], "tags": "internet, share, viral, connect"},
    {"name": "xanthic", "word": "Xanthic", "letter": "X", "meaning": "Yellow or yellowish", "rap_meaning": "Gold, blonde hair, yellow diamonds, caution", "syllables": "2 (xan-thic)", "pos": "Adjective", "synonyms": "Yellow, gold", "antonyms": "Dark", "rhymes": "END: atlantic, romantic, frantic / SLANT: sick / MULTI: gigantic", "bars": ["Xanthic diamonds, canary yellow shine", "Everything xanthic, gold rush fever", "Xanthic tape around the body, caution"], "punchlines": ["Color of gold", "Caution tape color", "Yellow bone slang"], "tags": "color, gold, yellow, shine"},
    {"name": "xebec", "word": "Xebec", "letter": "X", "meaning": "A small three-masted Mediterranean sailing ship", "rap_meaning": "Your boat/yacht, sailing the seas, pirate lifestyle", "syllables": "2 (xe-bec)", "pos": "Noun", "synonyms": "Ship, boat", "antonyms": "Land", "rhymes": "END: deck, check, neck, wreck / SLANT: back / MULTI: quebec", "bars": ["Pull up in the Xebec, mediterranean flow", "Captain of the Xebec, pirating the streams", "Sailing past you in a Xebec while you row"], "punchlines": ["Pirate ship imagery", "Yacht life", "Obscure boat flex"], "tags": "boat, sea, travel, rich"},
    {"name": "xenial", "word": "Xenial", "letter": "X", "meaning": "Relating to hospitality between host and guest", "rap_meaning": "Treating guests right, running the trap house efficiently, fake hospitality", "syllables": "3 (xe-ni-al)", "pos": "Adjective", "synonyms": "Hospitality, welcoming", "antonyms": "Hostile", "rhymes": "END: denial, trial, dial / SLANT: all / MULTI: millennial", "bars": ["Xenial vibes when you enter the mansion", "Don't mistake my xenial nature for weakness", "Serve 'em with that xenial smile then take the cash"], "punchlines": ["Host with the most", "House rules", "Fake welcome"], "tags": "welcome, house, manners, fake"},
    {"name": "xenolith", "word": "Xenolith", "letter": "X", "meaning": "A piece of rock within an igneous rock", "rap_meaning": "Hard core inside, foreign object, diamond in the rough", "syllables": "3 (xen-o-lith)", "pos": "Noun", "synonyms": "Rock, stone", "antonyms": "None", "rhymes": "END: myth, smith, pith / SLANT: with / MULTI: monolith", "bars": ["Heart hard like a xenolith inside the lava", "Foreign rock, call it a xenolith diamond", "Found the xenolith, rare gem in the dirt"], "punchlines": ["Geology metaphor", "Hard heart", "Rare find"], "tags": "rock, hard, rare, geology"},
    {"name": "xenophile", "word": "Xenophile", "letter": "X", "meaning": "One who is attracted to foreign things", "rap_meaning": "Loves foreign cars, foreign clothes, traveling the world", "syllables": "3 (xen-o-phile)", "pos": "Noun", "synonyms": "Traveler, explorer", "antonyms": "Xenophobe", "rhymes": "END: style, mile, pile, smile / SLANT: ill / MULTI: versatility", "bars": ["Certified xenophile, only drive imports", "Xenophile taste, italian leather on the seats", "Passport full of stamps, I'm a xenophile"], "punchlines": ["Foreign car obsession", "International dating", "Exotic taste"], "tags": "foreign, travel, cars, taste"},
    {"name": "xeriscaping", "word": "Xeriscaping", "letter": "X", "meaning": "Landscaping that saves water", "rap_meaning": "Efficient grinding, no waste, surviving the drought", "syllables": "4 (xer-i-scap-ing)", "pos": "Noun", "synonyms": "Conservation, dry-garden", "antonyms": "Waste", "rhymes": "END: gaping, taping, draping / SLANT: happen / MULTI: escaping", "bars": ["Xeriscaping the budget, we don't waste a drop", "Survive the drought like xeriscaping roots", "Green in the desert, that's xeriscaping"], "punchlines": ["Drought survival", "Efficiency with resources", "Desert flower"], "tags": "money, save, survive, dry"},
    {"name": "xeric", "word": "Xeric", "letter": "X", "meaning": "Characterized by a small supply of moisture; dry", "rap_meaning": "Thirsty haters, dry snitching, desolate environment", "syllables": "2 (xer-ic)", "pos": "Adjective", "synonyms": "Dry, arid", "antonyms": "Wet", "rhymes": "END: lyric, generic, numeric / SLANT: brick / MULTI: hysteric", "bars": ["Your flow xeric, dusty and dry", "Leave 'em in a xeric state, thirsty for clout", "Xeric environment, only the strong cactus survives"], "punchlines": ["Thirst trap", "Dry personality/flow", "Desert survival"], "tags": "dry, thirsty, weak, desert"},
    {"name": "xerosis", "word": "Xerosis", "letter": "X", "meaning": "Abnormal dryness of skin or eyes", "rap_meaning": "Rough skin from the hustle, eyes dry from no sleep, ashy", "syllables": "3 (xe-ro-sis)", "pos": "Noun", "synonyms": "Dryness", "antonyms": "Moisture", "rhymes": "END: hypnosis, doses, roses / SLANT: focus / MULTI: diagnosis", "bars": ["Hands rough with xerosis from counting bills", "Eyes red with xerosis, watching the door", "You soft, I got xerosis from the cold wind"], "punchlines": ["Hard work hands", "No lotion (ashy)", "Struggle signs"], "tags": "dry, struggle, work, body"},
    {"name": "x-height", "word": "X-height", "letter": "X", "meaning": "The height of lowercase letters", "rap_meaning": "Small print, reading the details in the contract, levels", "syllables": "2 (x-height)", "pos": "Noun", "synonyms": "Size, print", "antonyms": "Caps", "rhymes": "END: light, bright, fight, night / SLANT: hate / MULTI: insight", "bars": ["Check the X-height on the contract before signing", "You playing at X-height, I'm all CAPS", "Details in the X-height, devil in the print"], "punchlines": ["Contract reading", "Typography size (getting big)", "Small vs Large"], "tags": "contract, details, small, read"},
    {"name": "x-axis", "word": "X-axis", "letter": "X", "meaning": "Horizontal axis in a graph", "rap_meaning": "Staying grounded (horizontal), flat-lining opposition, running the baseline", "syllables": "3 (x-ax-is)", "pos": "Noun", "synonyms": "Horizontal, ground", "antonyms": "Y-axis", "rhymes": "END: practice, cactus, tactics / SLANT: ashes / MULTI: galactic", "bars": ["Running along the X-axis, covering the ground", "Flatline you on the X-axis, zero pulse", "Expand on the X-axis, wide reach globally"], "punchlines": ["Math graph imagery", "Flatline (ECG)", "Wide territory"], "tags": "math, ground, flat, graph"},
    {"name": "xbox", "word": "Xbox", "letter": "X", "meaning": "Video game console", "rap_meaning": "Playing games, controlling players, console wars", "syllables": "2 (x-box)", "pos": "Noun", "synonyms": "Console, game", "antonyms": "Playstation", "rhymes": "END: hotbox, lockbox, sox / SLANT: rocks / MULTI: detox", "bars": ["Hotbox the coupe playing Xbox with your life", "No Xbox, I don't play games with money", "Controller disconnected, your Xbox turned off"], "punchlines": ["Game over", "Controller metaphor", "Hotbox rhyme"], "tags": "game, play, control, fun"},
    {"name": "x-class", "word": "X-class", "letter": "X", "meaning": "A class of solar flares; Mercedes truck", "rap_meaning": "Explosive power, Mercedes Benz X-Class, top tier", "syllables": "2 (x-class)", "pos": "Noun", "synonyms": "Flare, truck", "antonyms": "None", "rhymes": "END: pass, glass, mass, grass / SLANT: fast / MULTI: bypass", "bars": ["Solar flare X-class, burning the atmosphere", "Pull up in the X-class Benz, heavy duty", "Level X-class, classified power"], "punchlines": ["Sun flare intensity", "Mercedes truck flex", "Class hierarchy"], "tags": "power, car, hot, top"},
    {"name": "xylograph", "word": "Xylograph", "letter": "X", "meaning": "A wood engraving", "rap_meaning": "Carved in wood (permanent), old school art, cutting deep", "syllables": "3 (xy-lo-graph)", "pos": "Noun", "synonyms": "Carving, print", "antonyms": "None", "rhymes": "END: photograph, autograph, paragraph / SLANT: laugh / MULTI: polygraph", "bars": ["Legacy carved like a xylograph, permanent marks", "Etched in the grain, xylograph style", "You just a sketch, I'm a xylograph masterpiece"], "punchlines": ["Carving metaphor", "Longevity (wood lasts)", "Artistic detail"], "tags": "art, permanent, wood, carve"},
    {"name": "xyloid", "word": "Xyloid", "letter": "X", "meaning": "Resembling wood; woody", "rap_meaning": "Stiff flow, wooden personality, or hard as oak", "syllables": "2 (xy-loid)", "pos": "Adjective",
    "synonyms": "Woody, stiff", "antonyms": "Flexible", "rhymes": "END: avoid, void, asteroid / SLANT: boy / MULTI: paranoid", "bars": ["Flow xyloid, stiff and brittle", "Heart xyloid, hard like petrified bark", "Don't be xyloid, bend with the wind"], "punchlines": ["Pinocchio imagery (wooden boy)", "Stiffness insult", "Hardness"], "tags": "wood, hard, stiff, insult"},
    {"name": "xyster", "word": "Xyster", "letter": "X", "meaning": "A surgical instrument for scraping bones", "rap_meaning": "Scraping the pot, getting to the bone, painful extraction", "syllables": "2 (xys-ter)", "pos": "Noun", "synonyms": "Scraper, tool", "antonyms": "None", "rhymes": "END: blister, sister, twister / SLANT: master / MULTI: resistor", "bars": ["Scrape the pot with a xyster, get every gram", "Cut to the bone like a xyster, truth hurts", "Xyster mentality, I scrape by until I win"], "punchlines": ["Medical horror", "Cooking crack metaphor (scraping)", "Deep pain"], "tags": "tool, pain, cook, bone"},
    {"name": "xystus", "word": "Xystus", "letter": "X", "meaning": "A covered walkway for exercise", "rap_meaning": "The path to success, prison yard walk, preparing for battle", "syllables": "2 (xys-tus)", "pos": "Noun", "synonyms": "Walkway, gym", "antonyms": "None", "rhymes": "END: justice, bust this, trust us / SLANT: dust / MULTI: adjust this", "bars": ["Walking down the Xystus, plotting my next move", "Exercise patience in the Xystus shade", "No safe Xystus in these streets, watch your back"], "punchlines": ["Roman architecture", "Prison yard imagery", "Path of preparation"], "tags": "path, walk, train, ancient"},
    {"name": "xoxo", "word": "XOXO", "letter": "X", "meaning": "Hugs and kisses", "rap_meaning": "Fake love, signing off letters, The Weeknd (XO), love/hate", "syllables": "4 (x-o-x-o)", "pos": "Noun", "synonyms": "Love, kiss", "antonyms": "Hate", "rhymes": "END: flow, go, slow, show / SLANT: yo / MULTI: logo", "bars": ["Signed it XOXO, kiss of death", "XO on the chain, rep the crew", "No XOXO for the enemies, just bullet holes"], "punchlines": ["Gossip Girl reference", "Kiss of death", "Weeknd crew reference"], "tags": "love, fake, crew, sign"},
    {"name": "xu", "word": "Xu", "letter": "X", "meaning": "A monetary unit of Vietnam", "rap_meaning": "Small change, foreign money, Vietnam connection", "syllables": "1 (xu)", "pos": "Noun", "synonyms": "Money, coin", "antonyms": "None", "rhymes": "END: do, who, you, crew / SLANT: new / MULTI: voodoo", "bars": ["Every Xu counts when you starving", "Stacking Xu or Dollars, money is money", "Don't treat me like a Xu, I'm the whole bank"], "punchlines": ["Small coin metaphor", "Value of everything", "Foreign currency"], "tags": "money, small, foreign, value"},
    {"name": "xylan", "word": "Xylan", "letter": "X", "meaning": "A yellow gummy substance from wood", "rap_meaning": "Sticky situation, glue holding it together, extracting value", "syllables": "2 (xy-lan)", "pos": "Noun", "synonyms": "Gum, resin", "antonyms": "None", "rhymes": "END: island, highland, silent / SLANT: man / MULTI: diamond", "bars": ["Stuck in the game like Xylan gum", "Extracting the Xylan, processing the goods", "Yellow Xylan, gold in the trees"], "punchlines": ["Sticky situations", "Chemistry/Processing", "Plant life"], "tags": "sticky, gum, plant, chemistry"},
    {"name": "xylem", "word": "Xylem", "letter": "X", "meaning": "Tissue in plants that conducts water", "rap_meaning": "The roots, the veins, the supply chain, staying hydrated/fed", "syllables": "2 (xy-lem)", "pos": "Noun", "synonyms": "Vein, root", "antonyms": "None", "rhymes": "END: phloem, poem, totem / SLANT: them / MULTI: modem", "bars": ["Xylem flow, bringing life from the dirt up", "Cut the xylem and the flower dies", "I'm the xylem of the hood, feeding everybody"], "punchlines": ["Biology metaphor (lifeblood)", "Supply chain", "Roots imagery"], "tags": "life, roots, feed, biology"},
    {"name": "xylitol", "word": "Xylitol", "letter": "X", "meaning": "A sugar substitute", "rap_meaning": "Fake sweet, artificial, toxic to dogs (haters)", "syllables": "3 (xy-li-tol)", "pos": "Noun", "synonyms": "Sweetener, fake-sugar", "antonyms": "Sugar", "rhymes": "END: doll, ball, call, wall / SLANT: tall / MULTI: alcohol", "bars": ["You sweet but fake like Xylitol", "Toxic to the dogs like Xylitol pills", "No sugar coating, no Xylitol, just raw"], "punchlines": ["Fake sweetness", "Poisoning the dogs", "Artificial vs Real"], "tags": "fake, sweet, toxic, food"},
    {"name": "xenote", "word": "Xenote", "letter": "X", "meaning": "Variant of Cenote; a sinkhole", "rap_meaning": "Deep hole, trap, diving into the unknown, hidden water", "syllables": "3 (xe-no-te)", "pos": "Noun", "synonyms": "Sinkhole, pit", "antonyms": "Mountain", "rhymes": "END: note, boat, goat, coat / SLANT: float / MULTI: remote", "bars": ["Deep like a Xenote, diving in the abyss", "Throw the evidence in the Xenote", "Trapped in a Xenote, climbing up the walls"], "punchlines": ["Mayan sacrifice pit", "Deep water", "Hiding spot"], "tags": "hole, water, deep, trap"},
    {"name": "x-ing", "word": "X-ing", "letter": "X", "meaning": "Crossing", "rap_meaning": "Crossing people out, pedestrian crossing (walk over you), crossroads", "syllables": "2 (x-ing)", "pos": "Verb/Noun", "synonyms": "Crossing, intersection", "antonyms": "Parallel", "rhymes": "END: king, ring, thing, wing / SLANT: bring / MULTI: boxing", "bars": ["X-ing out the names on the list", "Catch me at the X-ing, crossroads demon", "No X-ing allowed, stay in your lane"], "punchlines": ["Hit list", "Road safety metaphor", "Crossroads deal"], "tags": "cross, kill, road, list"},
    {"name": "x-series", "word": "X-series", "letter": "X", "meaning": "BMW SUV series", "rap_meaning": "Driving the X5, X6, luxury trucks", "syllables": "3 (x-se-ries)", "pos": "Noun", "synonyms": "Bmw, truck", "antonyms": "Hooptie", "rhymes": "END: theories, queries, weary / SLANT: see / MULTI: diaries", "bars": ["Pull up in the X-series, tint dark", "X-series BMW, sliding on the highway", "Upgrade to the X-series, boss moves"], "punchlines": ["Car flex", "German engineering", "Series model"], "tags": "car, bmw, rich, drive"},
    {"name": "x-type", "word": "X-type", "letter": "X", "meaning": "Jaguar car model", "rap_meaning": "Jaguar, exotic car, specific type of person", "syllables": "2 (x-type)", "pos": "Noun", "synonyms": "Jaguar, car", "antonyms": "None", "rhymes": "END: hype, wipe, pipe, stripe / SLANT: lip / MULTI: prototype", "bars": ["Jaguar X-type, purring in the lot", "She my X-type, exotic and fast", "Not your average X-type, I'm a prototype"], "punchlines": ["Car flex", "Type of girl/guy", "Prototype"], "tags": "car, jaguar, type, rare"},
    {"name": "x-wing", "word": "X-wing", "letter": "X", "meaning": "Starfighter from Star Wars", "rap_meaning": "Spaceship whip, dogfight, rebellion, futuristic", "syllables": "2 (x-wing)", "pos": "Noun", "synonyms": "Starfighter, ship", "antonyms": "Tie-fighter", "rhymes": "END: king, ring, swing, thing / SLANT: wing / MULTI: boxing", "bars": ["Space coupe look like an X-wing fighter", "Locked S-foils in attack position, X-wing", "Rebel leader in the X-wing, destroying death stars"], "punchlines": ["Star Wars reference", "Futuristic car", "Leader of rebellion"], "tags": "space, car, fight, nerd"},
    {"name": "x-pert", "word": "X-pert", "letter": "X", "meaning": "Expert (stylized)", "rap_meaning": "Master of the craft, pro, highly skilled", "syllables": "2 (x-pert)", "pos": "Noun", "synonyms": "Master, pro", "antonyms": "Novice", "rhymes": "END: hurt, dirt, shirt, skirt / SLANT: start / MULTI: concert", "bars": ["Call me the X-pert, I wrote the manual", "X-pert witness on the stand, I know the game", "Ask the X-pert before you touch the stove"], "punchlines": ["Subject matter expert", "Stylized spelling", "Mastery claim"], "tags": "slang, smart, master, pro"},
    {"name": "x-cel", "word": "X-cel", "letter": "X", "meaning": "Excel (stylized)", "rap_meaning": "To do better, spreadsheet handling (money), going up", "syllables": "2 (x-cel)", "pos": "Verb", "synonyms": "Succeed, shine", "antonyms": "Fail", "rhymes": "END: bell, hell, sell, tell / SLANT: well / MULTI: hotel", "bars": ["Watch me X-cel past the limits", "Spreadsheets X-cel, tracking the profit", "Born to X-cel, mediocrity is a sin"], "punchlines": ["Microsoft Excel pun", "Rising above", "Stylized spelling"], "tags": "slang, success, money, rise"},
    {"name": "x-tra", "word": "X-tra", "letter": "X", "meaning": "Extra (stylized)", "rap_meaning": "Doing the most, extra money, extra rounds, newspaper boy", "syllables": "2 (x-tra)", "pos": "Adjective", "synonyms": "More, surplus", "antonyms": "Less", "rhymes": "END: play, day, way / SLANT: star / MULTI: orchestra", "bars": ["Read all about it, X-tra X-tra", "Need X-tra large pockets for this cash", "You being X-tra, calm down with the drama"], "punchlines": ["Newspaper cry", "Size references", "Drama queen"], "tags": "slang, big, drama, news"},
    {"name": "xenogenesis", "word": "Xenogenesis", "letter": "X", "meaning": "Production of offspring unlike parents", "rap_meaning": "I'm nothing like my parents/origins, built different, mutant generation", "syllables": "5 (xen-o-gen-e-sis)", "pos": "Noun", "synonyms": "Mutation, evolution", "antonyms": "Cloning", "rhymes": "END: nemesis, premises, synthesis / SLANT: this / MULTI: parenthesis", "bars": ["Xenogenesis, I came from the dirt but I'm gold", "A complete new species, xenogenesis flow", "My origin story is xenogenesis, unexplained"], "punchlines": ["Octavia Butler reference (Sci-fi)", "Built different", "Evolutionary leap"], "tags": "change, evolution, different, sci-fi"},
]

def create_word(word_data):
    letter = word_data["letter"]
    letter_path = Path(BASE_PATH) / letter
    words_base_path = letter_path / "01_Words"
    words_base_path.mkdir(parents=True, exist_ok=True)
    word_folder = words_base_path / word_data["name"]
    word_folder.mkdir(exist_ok=True)

    template = f"""# WORD: {word_data["word"]}

## Meaning (plain):
{word_data["meaning"]}

## Rap meaning (how I'd say it):
{word_data["rap_meaning"]}

## Syllables:
{word_data["syllables"]}

## Part of speech:
{word_data["pos"]}

## Synonyms:
{word_data["synonyms"]}

## Antonyms:
{word_data["antonyms"]}

## Rhyme ideas (end / slant / multi):
{word_data["rhymes"]}

## 3 bar-ready examples:
1. {word_data["bars"][0]}
2. {word_data["bars"][1]}
3. {word_data["bars"][2]}

## 3 punchline angles:
1. {word_data["punchlines"][0]}
2. {word_data["punchlines"][1]}
3. {word_data["punchlines"][2]}

## Tags:
{word_data["tags"]}
"""
    word_file = word_folder / "word.md"
    word_file.write_text(template, encoding='utf-8')
    print(f"[+] Created: {letter}/{word_data['name']}")

def main():
    print(f"Adding 40 remaining X words...")
    for word_data in WORDS:
        create_word(word_data)
    print(f"Done with X.")

if __name__ == "__main__":
    main()
