import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

const audioDir = path.resolve(__dirname, '../public/audio');
const outputFile = path.resolve(__dirname, '../src/lib/data/tracks.js');

function scanTracks() {
  if (!fs.existsSync(audioDir)) {
    console.log('Audio directory not found, creating it...');
    fs.mkdirSync(audioDir, { recursive: true });
    return;
  }

  const files = fs.readdirSync(audioDir);
  const tracks = files
    .filter(file => /\.(mp3|wav|m4a|ogg)$/i.test(file))
    .map(file => ({
      title: path.parse(file).name,
      src: `/audio/${file}`
    }));

  const content = `// This file is auto-generated by scan-tracks.js
export const tracks = ${JSON.stringify(tracks, null, 2)};
`;

  fs.writeFileSync(outputFile, content);
  console.log(`🎵 Track list updated! Found ${tracks.length} tracks.`);
}

scanTracks();
