import React, { useEffect, useState } from 'react';
import { useParams, Link } from 'react-router-dom';

const DomainView = () => {
  const { domain } = useParams();
  const [entities, setEntities] = useState([]);
  const [loading, setLoading] = useState(true);

  useEffect(() => {
     // In a real app we would fetch the manifest or list from an API.
     // Since this is static, we might need a manifest.json generated by sync-data.
     // For now, let's try to fetch the manifest if it exists, or just show a placeholder.
     
     fetch('/data/manifest.json')
      .then(res => res.json())
      .then(manifest => {
          // Ideally manifest would list all files. 
          // If not, we might scan specific known files or just show the structure.
          console.log("Loaded manifest", manifest);
          setLoading(false);
      })
      .catch(err => {
          console.error("Failed to load manifest", err);
          setLoading(false);
      });
  }, [domain]);

  return (
    <div className="page-container">
      <h1>DOMAIN: {domain.toUpperCase()}</h1>
      <Link to="/hub" className="back-link">← BACK</Link>
      
      {loading ? (
        <div className="loading">LOADING DATA...</div>
      ) : (
        <div className="entity-list">
             {/* Placeholder for list */}
             <div className="card">
                 <h3>Constructing Index...</h3>
                 <p>Scanning neuro-net for {domain} entities.</p>
             </div>
        </div>
      )}
    </div>
  );
};

export default DomainView;
