#!/usr/bin/env python3
import os
import sys
from pathlib import Path

# Fix Windows console encoding
if sys.platform == 'win32':
    sys.stdout.reconfigure(encoding='utf-8')

BASE_PATH = r"C:\Users\JaZeR\OneDrive\Desktop\2026 → JaZeR Mainframe\2026 → JaZeR Master Flow Knowledge Hub\Rap_Dictionary_Master_Hub"

# 40 New Z Words to reach 50 total
WORDS = [
    {"name": "zap", "word": "Zap", "letter": "Z", "meaning": "To destroy or hit with sudden force", "rap_meaning": "To take someone out quickly, sudden impact, laser focus", "syllables": "1 (zap)", "pos": "Verb", "synonyms": "Strike, hit, destroy, shock", "antonyms": "Miss, ignore", "rhymes": "END: trap, rap, map, cap, clap / SLANT: step, rep / MULTI: mishap, kidnap", "bars": ["Zap the enemies like bugs in the light", "Sudden zap to the system, wake 'em up", "I don't argue, I just zap and move on"], "punchlines": ["Electric chair imagery", "Bug zapper metaphor", "Laser sound effects"], "tags": "fast, violence, shock, hit"},
    {"name": "zany", "word": "Zany", "letter": "Z", "meaning": "Amusingly unconventional and idiosyncratic", "rap_meaning": "Crazy style, wild flows, unpredictable personality", "syllables": "2 (za-ny)", "pos": "Adjective", "synonyms": "Eccentric, crazy, wild, goofy", "antonyms": "Serious, boring, normal", "rhymes": "END: rainy, brainy, grainy / SLANT: penny, many / MULTI: miscellany", "bars": ["Style zany, they can't predict the pattern", "Zany with the bars, I'm laughing to the bank", "Call me zany cause I refuse to be normal"], "punchlines": ["Clown/Joker imagery", "Mental instability flex", "Cartoon physics"], "tags": "crazy, style, wild, fun"},
    {"name": "zealot", "word": "Zealot", "letter": "Z", "meaning": "A person who is fanatical and uncompromising in pursuit of their ideals", "rap_meaning": "Die-hard fan, obsessed grinder, someone religiously dedicated to the game", "syllables": "2 (zeal-ot)", "pos": "Noun", "synonyms": "Fanatic, extremist, devotee", "antonyms": "Moderate, doubter", "rhymes": "END: pellet, smell it, sell it / SLANT: wallet, ballot / MULTI: propellant", "bars": ["Move like a zealot, I worship the hustle", "Zealots following my wave like a religion", "No compromise, I'm a zealot for the truth"], "punchlines": ["Religious cult leader imagery", "Uncompromising nature", "Fanatical dedication"], "tags": "dedication, obsessed, fan, intense"},
    {"name": "zebra", "word": "Zebra", "letter": "Z", "meaning": "African wild horse with black-and-white stripes", "rap_meaning": "Referees (zebras), black and white situation, prison bars, or rare prints", "syllables": "2 (ze-bra)", "pos": "Noun", "synonyms": "Stripes, horse, equine", "antonyms": "None", "rhymes": "END: algebra, libra / SLANT: fever, beaver / MULTI: candelabra", "bars": ["Stripes on me like a zebra, designer prints", "Watch out for the zebras, they flagging the play", "Life ain't black and white like a zebra, it's gray"], "punchlines": ["Referee metaphor (hating on the play)", "Prison outfit (stripes)", "Prey vs Predator"], "tags": "animal, stripes, referee, fashion"},
    {"name": "zeitgeist", "word": "Zeitgeist", "letter": "Z", "meaning": "The defining spirit or mood of a particular period of history", "rap_meaning": "Capturing the moment, being the current wave, defining the era", "syllables": "2 (zeit-geist)", "pos": "Noun", "synonyms": "Spirit, mood, trend, era", "antonyms": "Past, history", "rhymes": "END: heist, priced, sliced, iced / SLANT: christ, mist / MULTI: poltergeist", "bars": ["I am the zeitgeist, look at me to see the future", "Captured the zeitgeist in a bottle and sold it", "Shift the zeitgeist with one verse, culture shaker"], "punchlines": ["Ghost of the times (geist)", "Trendsetting", "Historian of the present"], "tags": "culture, time, trend, spirit"},
    {"name": "zeppelin", "word": "Zeppelin", "letter": "Z", "meaning": "A large German dirigible airship", "rap_meaning": "Staying high, heavy metal (Led Zeppelin), big ego floating above", "syllables": "3 (zep-pe-lin)", "pos": "Noun", "synonyms": "Airship, blimp, balloon", "antonyms": "Submarine", "rhymes": "END: adrenaline, medicine, melanin / SLANT: step in, weapon / MULTI: discipline", "bars": ["High as a zeppelin, looking down at the ants", "Explosive flow like a zeppelin, Hindenburg bars", "Lead Zeppelin heavy metal on my waist"], "punchlines": ["Hindenburg disaster (blowing up)", "Floating above competition", "Rock band reference"], "tags": "fly, high, big, explosion"},
    {"name": "zest", "word": "Zest", "letter": "Z", "meaning": "Great enthusiasm and energy", "rap_meaning": "Flavor, sauce, energy, adding spice to the game", "syllables": "1 (zest)", "pos": "Noun", "synonyms": "Flavor, spice, energy, gusto", "antonyms": "Bland, apathy", "rhymes": "END: best, chest, west, test, blessed / SLANT: fast, past / MULTI: manifest, interest", "bars": ["Add a little zest to the flow, make it tasty", "Living with zest, everyday a celebration", "No zest in your raps, they taste like water"], "punchlines": ["Cooking metaphor (adding spice)", "Life energy", "Lemon peel imagery"], "tags": "energy, flavor, style, spice"},
    {"name": "zig", "word": "Zig", "letter": "Z", "meaning": "A sharp change of direction", "rap_meaning": "To move differently, when they zag you zig, unpredictability", "syllables": "1 (zig)", "pos": "Verb", "synonyms": "Turn, swerve, veer", "antonyms": "Straight", "rhymes": "END: big, dig, rig, pig, wig / SLANT: leg, bag / MULTI: shindig", "bars": ["When they zag, I zig, never follow the crowd", "Zig-zagging through the lawsuits and the hate", "One zig and you missed me, too fast"], "punchlines": ["Evasion tactics", "Contrarian movement", "Pattern breaking"], "tags": "move, dodge, different, fast"},
    {"name": "zillion", "word": "Zillion", "letter": "Z", "meaning": "An extremely large indeterminate number", "rap_meaning": "Infinite money, endless potential, too many to count", "syllables": "2 (zil-lion)", "pos": "Noun", "synonyms": "Bazillion, gazillion, infinite", "antonyms": "Zero, few", "rhymes": "END: million, billion, trillion, pavilion / SLANT: villain / MULTI: civilian, vermilion", "bars": ["Trying to touch a zillion before I touch a coffin", "Got a zillion problems but money ain't one", "Zillion possibilities when you open your mind"], "punchlines": ["Hyperbole for wealth", "Uncountable stats", "Math breaking"], "tags": "money, huge, numbers, infinite"},
    {"name": "zinc", "word": "Zinc", "letter": "Z", "meaning": "A chemical element; a blue-white metal", "rap_meaning": "Metals (guns), chemistry, health (vitamins), hardening protection", "syllables": "1 (zinc)", "pos": "Noun", "synonyms": "Metal, element, mineral", "antonyms": "None", "rhymes": "END: sink, link, pink, drink, think / SLANT: bank, rank / MULTI: instinct, distinct", "bars": ["Heavy metal like zinc, keep the immune system strong", "Cold as zinc plating, armor for the heart", "Chemistry in the lab, mixing zinc with the fire"], "punchlines": ["Periodic table reference", "Galvanization (protection)", "Vitamin supplement (staying healthy)"], "tags": "metal, science, health, strong"},
    {"name": "zing", "word": "Zing", "letter": "Z", "meaning": "Energy, enthusiasm, or liveliness", "rap_meaning": "Sharp insults (zingers), energy, electric feeling", "syllables": "1 (zing)", "pos": "Noun/Verb",
    "synonyms": "Energy, pep, spark, bite", "antonyms": "Dullness", "rhymes": "END: king, ring, sing, wing, bring / SLANT: thing, bang / MULTI: uprising", "bars": ["Lyrics got that zing, hit you in the nerve", "Feel the zing when I walk in, static electricity", "Zing 'em with the truth, watch 'em recoil"], "punchlines": ["Electrical shock", "Insult comedy", "Taste buds reaction"], "tags": "energy, shock, insult, bite"},
    {"name": "zion", "word": "Zion", "letter": "Z", "meaning": "The hill of Jerusalem; a place of peace and utopia", "rap_meaning": "Promised land, matrix reference (last human city), ultimate goal/heaven", "syllables": "2 (zi-on)", "pos": "Noun", "synonyms": "Paradise, heaven, utopia, home", "antonyms": "Hell, babylon", "rhymes": "END: lion, iron, ryan / SLANT: line, mine / MULTI: mayan, hawaiian", "bars": ["Marching to Zion, looking for the promised land", "I'm a lion in Zion, king of the holy city", "Escaped the matrix, welcome to Zion"], "punchlines": ["Matrix trilogy reference", "Biblical promised land", "Rastafarian usage (Babylon vs Zion)"], "tags": "paradise, goal, holy, freedom"},
    {"name": "zip", "word": "Zip", "letter": "Z", "meaning": "To fasten; speed; nothing; a compressed file", "rap_meaning": "Zip lock bags (drugs), move fast, shut up (zip it), compressed code", "syllables": "1 (zip)", "pos": "Verb/Noun", "synonyms": "Fasten, rush, nothing, zero", "antonyms": "Open, slow", "rhymes": "END: trip, hip, sip, drip, flip / SLANT: step, keep / MULTI: ownership, relationship", "bars": ["Zip the bag, seal the deal, move the product", "Zip past the cops, they didn't even see the plates", "Zip your lips when the Gs are talking"], "punchlines": ["Drug packaging (ziplock)", "Speed lines", "Silence command"], "tags": "fast, shut-up, packaging, drugs"},
    {"name": "zipper", "word": "Zipper", "letter": "Z", "meaning": "A device for fastening clothes", "rap_meaning": "Closing mouths, keeping secrets, fastening the bag/money", "syllables": "2 (zip-per)", "pos": "Noun", "synonyms": "Fastener, closure", "antonyms": "Opening", "rhymes": "END: dipper, skipper, flipper, clipper / SLANT: paper, vapor / MULTI: big dipper", "bars": ["Got a zipper on the mouth, I don't snitch ever", "Caught in the zipper of the law, tried to break free", "Unzip the bag, let the aroma fill the room"], "punchlines": ["Snitching metaphor (zipped lips)", "Bag opening reveal", "Clothing malfunction"], "tags": "silence, secrets, clothes, bag"},
    {"name": "zircon", "word": "Zircon", "letter": "Z", "meaning": "A mineral, often used as a diamond simulant", "rap_meaning": "Fake diamonds (cubic zirconia), trying to look real but failing, cheap imitation", "syllables": "2 (zir-con)", "pos": "Noun", "synonyms": "Gem, crystal, fake", "antonyms": "Diamond", "rhymes": "END: silicon, hexagon, pentagon / SLANT: gone, dawn / MULTI: phenomenon", "bars": ["You rocking zircon, I'm rocking VVS natural", "Shine like a diamond but you just a zircon fraud", "Pressure makes diamonds, you crumbled into zircon"], "punchlines": ["Fake jewelry expose", "Real vs Synthetic", "Value comparison"], "tags": "fake, jewelry, cheap, imitation"},
    {"name": "zither", "word": "Zither", "letter": "Z", "meaning": "A musical instrument with many strings", "rap_meaning": "Pulling strings, complex melodies, old school vibe", "syllables": "2 (zith-er)", "pos": "Noun", "synonyms": "Instrument, strings", "antonyms": "Drum", "rhymes": "END: wither, hither, slither, dither / SLANT: river, shiver / MULTI: deliver", "bars": ["Play the game like a zither, pulling all the strings", "Harmonics on the zither, ancient melodies flowing", "You wither while I play the zither of destiny"], "punchlines": ["Puppet master string pulling", "Obscure instrument flex", "Snake/Slither rhyme scheme"], "tags": "music, strings, control, art"},
    {"name": "zloty", "word": "Zloty", "letter": "Z", "meaning": "The basic monetary unit of Poland", "rap_meaning": "Foreign money, international hustler, stacking currencies", "syllables": "2 (zlo-ty)", "pos": "Noun", "synonyms": "Currency, money, cash", "antonyms": "None", "rhymes": "END: floaty, throaty, coaty / SLANT: naughty, haughty / MULTI: coyote, quixote", "bars": ["Counting Zloty in Warsaw, global with the business", "Euro to Zloty, exchange rate favoring the boss", "Different colors of money, stacks of Zloty high"], "punchlines": ["International wire transfer", "Exotic currency efficiency", "Travel flex"], "tags": "money, foreign, currency, global"},
    {"name": "zonk", "word": "Zonk", "letter": "Z", "meaning": "To fall asleep or lose consciousness; to hit", "rap_meaning": "Knocked out, high and passed out, exhausted from grind", "syllables": "1 (zonk)", "pos": "Verb", "synonyms": "Sleep, crash, hit, conk", "antonyms": "Wake, alert", "rhymes": "END: honk, bonk, monk / SLANT: trunk, funk / MULTI: chipmunk", "bars": ["Zonk out on the flight, wake up in a new zone", "Took one hit and he zonk, glass jaw shattered", "Don't zonk on the opportunity, stay woke"], "punchlines": ["KO punch sound effect", "Drug induced sleep", "Game show reference (Zonked)"], "tags": "sleep, ko, punched, tired"},
    {"name": "zoomer", "word": "Zoomer", "letter": "Z", "meaning": "A member of Generation Z", "rap_meaning": "The new generation, young shooters, internet savvy, moving fast", "syllables": "2 (zoom-er)", "pos": "Noun", "synonyms": "Gen-Z, youth, youngster", "antonyms": "Boomer", "rhymes": "END: rumor, humor, tumor, bloomer / SLANT: summer, drummer / MULTI: consumer", "bars": ["OK Boomer, make way for the Zoomer takeover", "Zoomer energy, we grew up with the internet", "Fast life like a Zoomer, attention span strictly minimal"], "punchlines": ["Generational war (Boomer vs Zoomer)", "Speed of technology", "New guard stepping up"], "tags": "youth, generation, new, fast"},
    {"name": "zulu", "word": "Zulu", "letter": "Z", "meaning": "A member of a South African people; the letter Z in radio alphabet", "rap_meaning": "Zulu Nation (Hip Hop history), warrior spirit, Zulu time (universal time)", "syllables": "2 (zu-lu)", "pos": "Noun", "synonyms": "Warrior, tribe, z-ray", "antonyms": "None", "rhymes": "END: guru, voodoo, tutu / SLANT: you, do / MULTI: honolulu", "bars": ["Universal Zulu Nation, paying homage to Bambaataa", "Warrior spirit like a Zulu, shield and spear ready", "Check the Zulu time, we operating globally"], "punchlines": ["Hip Hop origins (Afrika Bambaataa)", "Military timing (Zulu time)", "African warrior heritage"], "tags": "history, culture, warrior, time"},
    {"name": "zygote", "word": "Zygote", "letter": "Z", "meaning": "A diploid cell resulting from the fusion of two haploid gametes", "rap_meaning": "The very beginning, since day one, potential life, small but growing", "syllables": "2 (zy-gote)", "pos": "Noun", "synonyms": "Embryo, seed, beginning", "antonyms": "Corpse, adult", "rhymes": "END: vote, coat, throat, boat / SLANT: goat, note / MULTI: antidote, anecdote", "bars": ["Been real since I was a zygote, it's in the DNA", "From a zygote to a god, watch the evolution", "Crush 'em before they develop, abort the zygote"], "punchlines": ["Biology/DNA reference", "Origin story (before birth)", "Potential vs Reality"], "tags": "life, beginning, dna, science"},
    {"name": "zapper", "word": "Zapper", "letter": "Z", "meaning": "A device that zaps; remote control", "rap_meaning": "The gun (heater), changing channels on people, controlling the game", "syllables": "2 (zap-per)", "pos": "Noun", "synonyms": "Remote, gun, laser", "antonyms": "None", "rhymes": "END: rapper, trapper, capper, dapper / SLANT: paper, vapor / MULTI: whippersnapper", "bars": ["Hand on the zapper, I change the channel on your life", "Keep the zapper close, mosquitoes trying to bite", "Video game zapper, casually shooting ducks"], "punchlines": ["TV Remote metaphor (tuning you out)", "NES Zapper gun reference", "Bug killer"], "tags": "gun, control, tech, shoot"},
    {"name": "zestful", "word": "Zestful", "letter": "Z", "meaning": "Characterized by great enthusiasm and energy", "rap_meaning": "Full of life, high energy performance, flavorful style", "syllables": "2 (zest-ful)", "pos": "Adjective",
    "synonyms": "Energetic, lively, spirited", "antonyms": "Dull, lifeless", "rhymes": "END: restful, chest full, best full / SLANT: stressful / MULTI: successful", "bars": ["Zestful living, I squeeze every drop out the day", "Flow zestful, burning your tongue with the spice", "Nothing stressful, just zestful, blessings on replay"], "punchlines": ["Lemon squeeze imagery", "Abundance of energy", "Taste metaphor"], "tags": "energy, happy, active, wild"},
    {"name": "zilch", "word": "Zilch", "letter": "Z", "meaning": "Nothing; zero", "rap_meaning": "You got nothing, empty pockets, zero stats", "syllables": "1 (zilch)", "pos": "Noun",
    "synonyms": "Nothing, zero, nada, zip", "antonyms": "Plenty, lot", "rhymes": "END: filch, milch / SLANT: filth, tilt / MULTI: quilt", "bars": ["You got zilch on me, no dirt to be found", "Started with zilch, now I'm filthy rich", "Your contribution is zilch, get out the session"], "punchlines": ["Comparison of haves and have-nots", "Clean record (zilch on me)", "From nothing to something"], "tags": "nothing, zero, empty, lack"},
    {"name": "zirconia", "word": "Zirconia", "letter": "Z", "meaning": "Cubic Zirconia; synthetic gem", "rap_meaning": "Fake jewelry, Fugazi, looking rich but broke", "syllables": "4 (zir-co-ni-a)", "pos": "Noun", "synonyms": "Fake diamond, crystal", "antonyms": "Diamond", "rhymes": "END: pneumonia, ammonia, estonia / SLANT: stone / MULTI: patagonia, begonia", "bars": ["Cubic zirconia shining, but it don't hold value", "Detect the zirconia from a mile away, no refraction", "Throat full of zirconia, lungs full of ammonia"], "punchlines": ["Jeweler's loupe verification", "Shame of wearing fakes", "Value retention argument"], "tags": "fake, jewelry, broke, fraud"},
    {"name": "zonal", "word": "Zonal", "letter": "Z", "meaning": "Relating to a zone", "rap_meaning": "Covering areas, defending territory (zonal marking), systematic control", "syllables": "2 (zo-nal)", "pos": "Adjective",
    "synonyms": "Regional, sectional", "antonyms": "Global", "rhymes": "END: tonal, hormonal, coronal / SLANT: bone / MULTI: personal", "bars": ["Zonal marking on the block, nothing gets through", "Thinking zonal but acting global", "System is zonal, every sector locked down"], "punchlines": ["Soccer defense strategy", "Territory control", "Grid management"], "tags": "control, area, defense, system"},
    {"name": "zoned", "word": "Zoned", "letter": "Z", "meaning": "Designated as a specific zone; high/intoxicated", "rap_meaning": "Zoned out (high), focused, or restricted area", "syllables": "1 (zoned)", "pos": "Adjective", "synonyms": "High, focused, assigned", "antonyms": "Alert, free", "rhymes": "END: owned, loaned, boned, toned / SLANT: round, sound / MULTI: postponed", "bars": ["Zoned out in the coupe, mind on another planet", "Commercially zoned, we doing big business here", "Zoned in on the target, laser dot steady"], "punchlines": ["Drug intoxication", "Real estate zoning laws", "Focus/Targeting"], "tags": "high, focus, space, business"},
    {"name": "zeus", "word": "Zeus", "letter": "Z", "meaning": "King of the gods in Greek mythology", "rap_meaning": "God tier, throwing lightning (bars), ruler of Olympus (the game)", "syllables": "1 (zeus)", "pos": "Noun", "synonyms": "God, king, ruler, thunder", "antonyms": "Mortal", "rhymes": "END: juice, loose, truce, noose, goose / SLANT: use, fuse / MULTI: produce, excuse", "bars": ["Feel like Zeus when I stand on the mountaintop", "Throwing lightning bolts, anger of Zeus unleashed", "Got the juice like Zeus, god of the sky"], "punchlines": ["Lightning bolt metaphors", "Olympus/God hierarchy", "Juice/Zeus rhyme"], "tags": "god, power, lightning, king"},
    {"name": "zaire", "word": "Zaire", "letter": "Z", "meaning": "Former name of Democratic Republic of the Congo", "rap_meaning": "Rumble in the Jungle (Ali vs Foreman), African roots, deep history", "syllables": "2 (za-ire)", "pos": "Noun", "synonyms": "Congo, DRC", "antonyms": "None", "rhymes": "END: fire, wire, hire, liar, tire / SLANT: air / MULTI: empire, desire", "bars": ["Rumble in Zaire, heavyweights trading blows", "Diamonds from Zaire, blood in the stone", "Heart of Africa, pulsing like Zaire drums"], "punchlines": ["Ali vs Foreman boxing reference", "Conflict diamonds", "Exotic location flex"], "tags": "place, history, boxing, africa"},
    {"name": "zambia", "word": "Zambia", "letter": "Z", "meaning": "Landlocked country in Southern Africa", "rap_meaning": "Exotic travel, resources, African connection", "syllables": "3 (zam-bi-a)", "pos": "Noun", "synonyms": "Africa", "antonyms": "None", "rhymes": "END: gambia, colombia / SLANT: ambush / MULTI: insomnia", "bars": ["Flew into Zambia just to see the falls", "Copper mines in Zambia, extracting the wealth", "Connected from Zambia to the Bronx"], "punchlines": ["Victoria Falls imagery", "Resource extraction", "Global connection"], "tags": "place, travel, africa, global"},
    {"name": "zimbabwe", "word": "Zimbabwe", "letter": "Z", "meaning": "Landlocked country in southern Africa", "rap_meaning": "Trillion dollar bills (inflation), ruins of empires, struggle and beauty", "syllables": "3 (zim-bab-we)", "pos": "Noun", "synonyms": "Rhodesia (historical)", "antonyms": "None", "rhymes": "END: highway, driveway, friday / SLANT: way / MULTI: hard way", "bars": ["Stacks looks like Zimbabwe currency, too many zeros", "Built like Great Zimbabwe, stone walls lasting forever", "From the struggle of Zimbabwe to the world stage"], "punchlines": ["Hyper-inflation (money worthless/worth a lot)", "Stone architecture (Great Zimbabwe)", "Political struggle"], "tags": "place, money, history, empire"},
    {"name": "zephyr", "word": "Zephyr", "letter": "Z", "meaning": "A soft gentle breeze", "rap_meaning": "Smooth flow, gentle touch, moving air, passing through easily", "syllables": "2 (zeph-yr)", "pos": "Noun", "synonyms": "Breeze, wind, air", "antonyms": "Gale, storm", "rhymes": "END: heifer, pepper / SLANT: never, sever / MULTI: endeavor, whenever", "bars": ["Flow smooth like a zephyr on a summer night", "Came through like a zephyr, barely made a sound", "Ride the zephyr to the top, effortless flight"], "punchlines": ["Wind/Air element control", "Contrast with storm/hardness", "Smoothness factor"], "tags": "wind, smooth, soft, flow"},
    {"name": "zen-garden", "word": "Zen-garden", "letter": "Z", "meaning": "A style of Japanese garden for meditation", "rap_meaning": "Perfectly raked sand (lines), peace, aesthetic, meticulous arrangement", "syllables": "3 (zen-gar-den)", "pos": "Noun", "synonyms": "Sanctuary, temple", "antonyms": "Chaos", "rhymes": "END: pardon, harden, warden / SLANT: margin / MULTI: avant-garde-in", "bars": ["Mind arranged like a zen-garden, perfect lines", "Raking in the cash in my zen-garden", "Step into my zen-garden, leave the shoes at the door"], "punchlines": ["Raking sand vs Raking cash", "Perfect order", "Peaceful setting"], "tags": "peace, order, money, mind"},
    {"name": "zero-sum", "word": "Zero-sum", "letter": "Z", "meaning": "A situation where one's gain is equivalent to another's loss", "rap_meaning": "I win you lose, ruthless game, no win-win, taking everything", "syllables": "3 (ze-ro-sum)", "pos": "Adjective", "synonyms": "Competitive, ruthless", "antonyms": "Win-win, cooperative", "rhymes": "END: dim sum, drum, hum / SLANT: some, come / MULTI: premium, delirium", "bars": ["It's a zero-sum game and I'm taking all the points", "No friends in zero-sum, I eat or you eat", "Zero-sum mentality, I need your plate to fill mine"], "punchlines": ["Game theory reference", "Ruthless competition", "Math of survival"], "tags": "game, ruthless, win, math"},
    {"name": "zillionaire", "word": "Zillionaire", "letter": "Z", "meaning": "An extremely wealthy person", "rap_meaning": "Richer than a billionaire, impossible wealth, goals", "syllables": "4 (zil-lion-aire)", "pos": "Noun", "synonyms": "Tycoon, magnate, rich", "antonyms": "Pauper", "rhymes": "END: millionaire, billionaire, extraordinaire / SLANT: air / MULTI: questionnaire", "bars": ["Unlisted bracket, call me zillionaire status", "Billionaire plays, zillionaire dreams", "Zillionaire boys club, membership exclusive"], "punchlines": ["Beyond Forbes list", "Inventing new tax brackets", "Wealth comparison"], "tags": "rich, money, wealth, goal"},
    {"name": "zoology", "word": "Zoology", "letter": "Z", "meaning": "Study of animals", "rap_meaning": "Studying the snakes and rats, understanding the streets (jungle), expertise in the game", "syllables": "4 (zo-ol-o-gy)", "pos": "Noun",
    "synonyms": "Biology, animal-science", "antonyms": "None", "rhymes": "END: biology, psychology, mythology, apology / SLANT: g / MULTI: ideology", "bars": ["Degree in street zoology, I know how the beasts move", "Studying the predators, master of zoology", "Zoology of the hood, it's a food chain"], "punchlines": ["Scientific study of the hood", "Animal behavior expert", "Predator vs Prey analysis"], "tags": "study, animals, streets, science"},
    {"name": "z-list", "word": "Z-list", "letter": "Z", "meaning": "The lowest tier of celebrity", "rap_meaning": "Irrelevant, nobody knows you, bottom of the barrel", "syllables": "2 (z-list)", "pos": "Noun/Adjective", "synonyms": "Nobody, unknown, scrub", "antonyms": "A-list, star", "rhymes": "END: fist, mist, wrist, twist / SLANT: list / MULTI: coexist, persist", "bars": ["You a Z-list rapper trying to beef with an icon", "Keep your Z-list energy away from the VIP", "From Z-list to A-list, the climb was vertical"], "punchlines": ["Celebrity hierarchy", "Irrelevance burn", "Alphabet ranking"], "tags": "status, fame, insult, bottom"},
    {"name": "zits", "word": "Zits", "letter": "Z", "meaning": "Pimples", "rap_meaning": "Popping them (problems/haters), blemishes on the record", "syllables": "1 (zits)", "pos": "Noun", "synonyms": "Pimples, acne, spots", "antonyms": "Clear", "rhymes": "END: fits, pits, bits, hits, wits / SLANT: gets, lets / MULTI: benefits", "bars": ["Pop you like zits, you just a blemish on the game", "Face messy with zits, clean up your act", "No zits on my record, skin flawless logic"], "punchlines": ["Dr. Pimple Popper imagery", "Hygiene insult", "Small annoyance removal"], "tags": "insult, gross, pop, clean"},
    {"name": "zinger", "word": "Zinger", "letter": "Z", "meaning": "A striking or amusing remark", "rap_meaning": "A punchline that hits hard, a roast, a sharp bar", "syllables": "2 (zing-er)", "pos": "Noun", "synonyms": "Quip, joke, roast, punchline", "antonyms": "Compliment", "rhymes": "END: singer, finger, linger, ringer / SLANT: anger / MULTI: dead ringer", "bars": ["Ended his career with one zinger", "Drop a zinger, crowd goes wild", "Zinger after zinger, lyrical comedian"], "punchlines": ["Comedy roast style", "Sharp tongue", "Knockout line"], "tags": "joke, punchline, funny, hit"},
    {"name": "zenith-point", "word": "Zenith-point", "letter": "Z", "meaning": "The exact point of the zenith", "rap_meaning": "The precise moment of peak success, hitting the mark", "syllables": "3 (ze-nith-point)", "pos": "Noun", "synonyms": "Peak, tip", "antonyms": "Nadir", "rhymes": "END: joint, anoint, disappoint / SLANT: point / MULTI: checkpoint", "bars": ["At the zenith-point, everything aligns perfectly", "Target the zenith-point, aim for the stars", "Balanced on the zenith-point, never falling off"], "punchlines": ["Geometry/Astronomy precision", "The perfect moment", "Top of the pyramid"], "tags": "peak, precision, top, goal"}, 
]

def create_word(word_data):
    letter = word_data["letter"]
    letter_path = Path(BASE_PATH) / letter
    words_base_path = letter_path / "01_Words"
    words_base_path.mkdir(parents=True, exist_ok=True)
    word_folder = words_base_path / word_data["name"]
    word_folder.mkdir(exist_ok=True)

    template = f"""# WORD: {word_data["word"]}

## Meaning (plain):
{word_data["meaning"]}

## Rap meaning (how I'd say it):
{word_data["rap_meaning"]}

## Syllables:
{word_data["syllables"]}

## Part of speech:
{word_data["pos"]}

## Synonyms:
{word_data["synonyms"]}

## Antonyms:
{word_data["antonyms"]}

## Rhyme ideas (end / slant / multi):
{word_data["rhymes"]}

## 3 bar-ready examples:
1. {word_data["bars"][0]}
2. {word_data["bars"][1]}
3. {word_data["bars"][2]}

## 3 punchline angles:
1. {word_data["punchlines"][0]}
2. {word_data["punchlines"][1]}
3. {word_data["punchlines"][2]}

## Tags:
{word_data["tags"]}
"""
    word_file = word_folder / "word.md"
    word_file.write_text(template, encoding='utf-8')
    print(f"[+] Created: {letter}/{word_data['name']}")

def main():
    print(f"Adding 40 remaining Z words...")
    for word_data in WORDS:
        create_word(word_data)
    print(f"Done with Z.")

if __name__ == "__main__":
    main()
